/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_clk_div_45.h"

        
void cm_clk_div_45(ARGS) 
{
	Digital_State_t *_op_clk_out, *_op_clk_out_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {   
        inst_count++;
        PARAM(instance_id)=inst_count;
        fooclk_div_45(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk_in=PORT_SIZE(clk_in);

        port_enable=PORT_SIZE(enable);

        port_clk_out=PORT_SIZE(clk_out);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(clk_in);Ii++)
		{
			LOAD(clk_in[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(enable);Ii++)
		{
			LOAD(enable[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_clk_out = _op_clk_out_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_clk_out = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_clk_out_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(clk_in);Ii++)
    {
        if( INPUT_STATE(clk_in[Ii])==ZERO )
        {
            temp_clk_in[Ii]=0;            }
        else
        {
            temp_clk_in[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(enable);Ii++)
    {
        if( INPUT_STATE(enable[Ii])==ZERO )
        {
            temp_enable[Ii]=0;            }
        else
        {
            temp_enable[Ii]=1;
        }
            }
	fooclk_div_45(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(clk_out);Ii++)
    {
        if(temp_clk_out[Ii]==0)
        {
            _op_clk_out[Ii]=ZERO;
            }
        else if(temp_clk_out[Ii]==1)
        {
            _op_clk_out[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(clk_out[Ii]) = _op_clk_out[Ii];
            }
        else if(_op_clk_out[Ii] != _op_clk_out_old[Ii])
        {
            OUTPUT_STATE(clk_out[Ii]) = _op_clk_out[Ii];
            OUTPUT_DELAY(clk_out[Ii]) = ((_op_clk_out[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(clk_out[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(clk_out[Ii]) = STRONG;
    }

}