/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_sev_seg.h"

        
void cm_sev_seg(ARGS) 
{
	Digital_State_t *_op_seg, *_op_seg_old;
	Digital_State_t *_op_en, *_op_en_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {   
        inst_count++;
        PARAM(instance_id)=inst_count;
        foosev_seg(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_dist=PORT_SIZE(dist);

        port_clk=PORT_SIZE(clk);

        port_seg=PORT_SIZE(seg);

        port_en=PORT_SIZE(en);
		cm_event_alloc(0,8*sizeof(Digital_State_t));
		cm_event_alloc(1,3*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(dist);Ii++)
		{
			LOAD(dist[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
		{
			LOAD(clk[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_seg = _op_seg_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_en = _op_en_old = (Digital_State_t *) cm_event_get_ptr(1,0);


	}
	else
	{
		_op_seg = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_seg_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_en = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_en_old = (Digital_State_t *) cm_event_get_ptr(1,2);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(dist);Ii++)
    {
        if( INPUT_STATE(dist[Ii])==ZERO )
        {
            temp_dist[Ii]=0;            }
        else
        {
            temp_dist[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
    {
        if( INPUT_STATE(clk[Ii])==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
	foosev_seg(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(seg);Ii++)
    {
        if(temp_seg[Ii]==0)
        {
            _op_seg[Ii]=ZERO;
            }
        else if(temp_seg[Ii]==1)
        {
            _op_seg[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(seg[Ii]) = _op_seg[Ii];
            }
        else if(_op_seg[Ii] != _op_seg_old[Ii])
        {
            OUTPUT_STATE(seg[Ii]) = _op_seg[Ii];
            OUTPUT_DELAY(seg[Ii]) = ((_op_seg[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(seg[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(seg[Ii]) = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(en);Ii++)
    {
        if(temp_en[Ii]==0)
        {
            _op_en[Ii]=ZERO;
            }
        else if(temp_en[Ii]==1)
        {
            _op_en[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(en[Ii]) = _op_en[Ii];
            }
        else if(_op_en[Ii] != _op_en_old[Ii])
        {
            OUTPUT_STATE(en[Ii]) = _op_en[Ii];
            OUTPUT_DELAY(en[Ii]) = ((_op_en[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(en[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(en[Ii]) = STRONG;
    }

}