int fooixorxnor(int,int);
        int temp_a[1024];
        int port_a;
        int temp_b[1024];
        int port_b;
        int temp_yXOR[1024];
        int port_yXOR;
        int temp_yXNOR[1024];
        int port_yXNOR;