#include "ngspice/cm.h"
extern void cm_jbasicgates(Mif_Private_t *);
/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_jbasicgates.h"

        
void cm_jbasicgates(Mif_Private_t *mif_private) 
{
	Digital_State_t *_op_yOR, *_op_yOR_old;
	Digital_State_t *_op_yAND, *_op_yAND_old;
	Digital_State_t *_op_yXOR, *_op_yXOR_old;
	Digital_State_t *_op_yNOR, *_op_yNOR_old;
	Digital_State_t *_op_yNAND, *_op_yNAND_old;
	Digital_State_t *_op_yXNOR, *_op_yXNOR_old;

    static int inst_count=0;
    int count=0;
        
    if(mif_private->circuit.init)
    {   
        inst_count++;
        mif_private->param[0]->element[0].rvalue=inst_count;
        foojbasicgates(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_a=mif_private->conn[0]->size;

        port_b=mif_private->conn[1]->size;

        port_yOR=mif_private->conn[2]->size;

        port_yAND=mif_private->conn[3]->size;

        port_yXOR=mif_private->conn[4]->size;

        port_yNOR=mif_private->conn[5]->size;

        port_yNAND=mif_private->conn[6]->size;

        port_yXNOR=mif_private->conn[7]->size;
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		cm_event_alloc(1,1*sizeof(Digital_State_t));
		cm_event_alloc(2,1*sizeof(Digital_State_t));
		cm_event_alloc(3,1*sizeof(Digital_State_t));
		cm_event_alloc(4,1*sizeof(Digital_State_t));
		cm_event_alloc(5,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
		{
			mif_private->conn[0]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
		{
			mif_private->conn[1]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}

		/*Retrieve Storage for output*/
		_op_yOR = _op_yOR_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_yAND = _op_yAND_old = (Digital_State_t *) cm_event_get_ptr(1,0);
		_op_yXOR = _op_yXOR_old = (Digital_State_t *) cm_event_get_ptr(2,0);
		_op_yNOR = _op_yNOR_old = (Digital_State_t *) cm_event_get_ptr(3,0);
		_op_yNAND = _op_yNAND_old = (Digital_State_t *) cm_event_get_ptr(4,0);
		_op_yXNOR = _op_yXNOR_old = (Digital_State_t *) cm_event_get_ptr(5,0);


	}
	else
	{
		_op_yOR = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_yOR_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_yAND = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_yAND_old = (Digital_State_t *) cm_event_get_ptr(1,2);
		_op_yXOR = (Digital_State_t *) cm_event_get_ptr(2,2);
		_op_yXOR_old = (Digital_State_t *) cm_event_get_ptr(2,3);
		_op_yNOR = (Digital_State_t *) cm_event_get_ptr(3,3);
		_op_yNOR_old = (Digital_State_t *) cm_event_get_ptr(3,4);
		_op_yNAND = (Digital_State_t *) cm_event_get_ptr(4,4);
		_op_yNAND_old = (Digital_State_t *) cm_event_get_ptr(4,5);
		_op_yXNOR = (Digital_State_t *) cm_event_get_ptr(5,5);
		_op_yXNOR_old = (Digital_State_t *) cm_event_get_ptr(5,6);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)mif_private->param[0]->element[0].rvalue;

    for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[0]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_a[Ii]=0;            }
        else
        {
            temp_a[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[1]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_b[Ii]=0;            }
        else
        {
            temp_b[Ii]=1;
        }
            }
	foojbasicgates(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
    {
        if(temp_yOR[Ii]==0)
        {
            _op_yOR[Ii]=ZERO;
            }
        else if(temp_yOR[Ii]==1)
        {
            _op_yOR[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[2]->port[Ii]->output.pvalue))->state = _op_yOR[Ii];
            }
        else if(_op_yOR[Ii] != _op_yOR_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[2]->port[Ii]->output.pvalue))->state = _op_yOR[Ii];
            mif_private->conn[2]->port[Ii]->delay = ((_op_yOR[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[2]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[2]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
    {
        if(temp_yAND[Ii]==0)
        {
            _op_yAND[Ii]=ZERO;
            }
        else if(temp_yAND[Ii]==1)
        {
            _op_yAND[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[3]->port[Ii]->output.pvalue))->state = _op_yAND[Ii];
            }
        else if(_op_yAND[Ii] != _op_yAND_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[3]->port[Ii]->output.pvalue))->state = _op_yAND[Ii];
            mif_private->conn[3]->port[Ii]->delay = ((_op_yAND[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[3]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[3]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
    {
        if(temp_yXOR[Ii]==0)
        {
            _op_yXOR[Ii]=ZERO;
            }
        else if(temp_yXOR[Ii]==1)
        {
            _op_yXOR[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[4]->port[Ii]->output.pvalue))->state = _op_yXOR[Ii];
            }
        else if(_op_yXOR[Ii] != _op_yXOR_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[4]->port[Ii]->output.pvalue))->state = _op_yXOR[Ii];
            mif_private->conn[4]->port[Ii]->delay = ((_op_yXOR[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[4]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[4]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
    {
        if(temp_yNOR[Ii]==0)
        {
            _op_yNOR[Ii]=ZERO;
            }
        else if(temp_yNOR[Ii]==1)
        {
            _op_yNOR[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[5]->port[Ii]->output.pvalue))->state = _op_yNOR[Ii];
            }
        else if(_op_yNOR[Ii] != _op_yNOR_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[5]->port[Ii]->output.pvalue))->state = _op_yNOR[Ii];
            mif_private->conn[5]->port[Ii]->delay = ((_op_yNOR[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[5]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[5]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
    {
        if(temp_yNAND[Ii]==0)
        {
            _op_yNAND[Ii]=ZERO;
            }
        else if(temp_yNAND[Ii]==1)
        {
            _op_yNAND[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[6]->port[Ii]->output.pvalue))->state = _op_yNAND[Ii];
            }
        else if(_op_yNAND[Ii] != _op_yNAND_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[6]->port[Ii]->output.pvalue))->state = _op_yNAND[Ii];
            mif_private->conn[6]->port[Ii]->delay = ((_op_yNAND[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[6]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[6]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
    {
        if(temp_yXNOR[Ii]==0)
        {
            _op_yXNOR[Ii]=ZERO;
            }
        else if(temp_yXNOR[Ii]==1)
        {
            _op_yXNOR[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[7]->port[Ii]->output.pvalue))->state = _op_yXNOR[Ii];
            }
        else if(_op_yXNOR[Ii] != _op_yXNOR_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[7]->port[Ii]->output.pvalue))->state = _op_yXNOR[Ii];
            mif_private->conn[7]->port[Ii]->delay = ((_op_yXNOR[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[7]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[7]->port[Ii]->output.pvalue))->strength = STRONG;
    }

}