/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vcounter8bit.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_rstn[1024];
        extern "C" int port_rstn;
        extern "C" int temp_out[1024];
        extern "C" int port_out;
        extern "C" int foocounter8bit(int,int);
        
        void int2arrcounter8bit(int  num, int array[], int n)
        {   
            for (int i = 0; i < n && num>=0; i++) 
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intcounter8bit(int array[],int n)
        {   
            int i,k=0;
            for (i = 0; i < n; i++) 
                k = 2 * k + array[i];
            return k;
        }
        
        int foocounter8bit(int init,int count) 
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vcounter8bit* counter8bit[1024];
            count--;
            if (init==0) 
            {
                counter8bit[count]=new Vcounter8bit{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============counter8bit : New Iteration===========");
                printf("\nInside foo before eval.....\n");
				printf("clk=%d\n", counter8bit[count] ->clk);
				printf("rstn=%d\n", counter8bit[count] ->rstn);
				printf("out=%d\n", counter8bit[count] ->out);
				counter8bit[count]->clk = arr2intcounter8bit(temp_clk, port_clk);
				counter8bit[count]->rstn = arr2intcounter8bit(temp_rstn, port_rstn);
				counter8bit[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("clk=%d\n", counter8bit[count] ->clk);
				printf("rstn=%d\n", counter8bit[count] ->rstn);
				printf("out=%d\n", counter8bit[count] ->out);
				int2arrcounter8bit(counter8bit[count] -> out, temp_out, port_out);

            }
            return 0;
        }