// Generated by SandPiper(TM) 1.11-2021/01/28-beta from Redwood EDA.
// Redwood EDA does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.
/* verilator lint_off UNUSED */

`include "sandpiper_gen.vh"


genvar dmem, imem, xreg;


//
// Signals declared top-level.
//

// For |cpu$br_tgt_pc.
logic [31:0] CPU_br_tgt_pc_a2,
             CPU_br_tgt_pc_a3;

// For |cpu$dec_bits.
logic [10:0] CPU_dec_bits_a1;

// For |cpu$dmem_addr.
logic [3:0] CPU_dmem_addr_a4;

// For |cpu$dmem_rd_data.
logic [31:0] CPU_dmem_rd_data_a4,
             CPU_dmem_rd_data_a5;

// For |cpu$dmem_rd_en.
logic CPU_dmem_rd_en_a4;

// For |cpu$dmem_wr_data.
logic [31:0] CPU_dmem_wr_data_a4;

// For |cpu$dmem_wr_en.
logic CPU_dmem_wr_en_a4;

// For |cpu$dummy.
logic [0:0] CPU_dummy_a0;

// For |cpu$funct3.
logic [2:0] CPU_funct3_a1;

// For |cpu$funct3_valid.
logic CPU_funct3_valid_a1;

// For |cpu$funct7.
logic [6:0] CPU_funct7_a1;

// For |cpu$funct7_valid.
logic CPU_funct7_valid_a1;

// For |cpu$imem_rd_addr.
logic [31:0] CPU_imem_rd_addr_a0,
             CPU_imem_rd_addr_a1;

// For |cpu$imem_rd_data.
logic [31:0] CPU_imem_rd_data_a1;

// For |cpu$imem_rd_en.
logic CPU_imem_rd_en_a0,
      CPU_imem_rd_en_a1;

// For |cpu$imm.
logic [31:0] CPU_imm_a1,
             CPU_imm_a2,
             CPU_imm_a3,
             CPU_imm_a4;

// For |cpu$inc_pc.
logic [31:0] CPU_inc_pc_a1,
             CPU_inc_pc_a2,
             CPU_inc_pc_a3;

// For |cpu$instr.
logic [31:0] CPU_instr_a1;

// For |cpu$is_add.
logic CPU_is_add_a1,
      CPU_is_add_a2,
      CPU_is_add_a3,
      CPU_is_add_a4;

// For |cpu$is_addi.
logic CPU_is_addi_a1,
      CPU_is_addi_a2,
      CPU_is_addi_a3,
      CPU_is_addi_a4;

// For |cpu$is_and.
logic CPU_is_and_a1,
      CPU_is_and_a2,
      CPU_is_and_a3,
      CPU_is_and_a4;

// For |cpu$is_andi.
logic CPU_is_andi_a1,
      CPU_is_andi_a2,
      CPU_is_andi_a3,
      CPU_is_andi_a4;

// For |cpu$is_auipc.
logic CPU_is_auipc_a1,
      CPU_is_auipc_a2,
      CPU_is_auipc_a3,
      CPU_is_auipc_a4;

// For |cpu$is_b_instr.
logic CPU_is_b_instr_a1;

// For |cpu$is_beq.
logic CPU_is_beq_a1,
      CPU_is_beq_a2,
      CPU_is_beq_a3,
      CPU_is_beq_a4,
      CPU_is_beq_a5;

// For |cpu$is_bge.
logic CPU_is_bge_a1,
      CPU_is_bge_a2,
      CPU_is_bge_a3,
      CPU_is_bge_a4,
      CPU_is_bge_a5;

// For |cpu$is_bgeu.
logic CPU_is_bgeu_a1,
      CPU_is_bgeu_a2,
      CPU_is_bgeu_a3,
      CPU_is_bgeu_a4,
      CPU_is_bgeu_a5;

// For |cpu$is_blt.
logic CPU_is_blt_a1,
      CPU_is_blt_a2,
      CPU_is_blt_a3,
      CPU_is_blt_a4,
      CPU_is_blt_a5;

// For |cpu$is_bltu.
logic CPU_is_bltu_a1,
      CPU_is_bltu_a2,
      CPU_is_bltu_a3,
      CPU_is_bltu_a4,
      CPU_is_bltu_a5;

// For |cpu$is_bne.
logic CPU_is_bne_a1,
      CPU_is_bne_a2,
      CPU_is_bne_a3,
      CPU_is_bne_a4,
      CPU_is_bne_a5;

// For |cpu$is_csrrc.
logic CPU_is_csrrc_a0,
      CPU_is_csrrc_a1,
      CPU_is_csrrc_a2,
      CPU_is_csrrc_a3,
      CPU_is_csrrc_a4;

// For |cpu$is_csrrci.
logic CPU_is_csrrci_a0,
      CPU_is_csrrci_a1,
      CPU_is_csrrci_a2,
      CPU_is_csrrci_a3,
      CPU_is_csrrci_a4;

// For |cpu$is_csrrs.
logic CPU_is_csrrs_a0,
      CPU_is_csrrs_a1,
      CPU_is_csrrs_a2,
      CPU_is_csrrs_a3,
      CPU_is_csrrs_a4;

// For |cpu$is_csrrsi.
logic CPU_is_csrrsi_a0,
      CPU_is_csrrsi_a1,
      CPU_is_csrrsi_a2,
      CPU_is_csrrsi_a3,
      CPU_is_csrrsi_a4;

// For |cpu$is_csrrw.
logic CPU_is_csrrw_a0,
      CPU_is_csrrw_a1,
      CPU_is_csrrw_a2,
      CPU_is_csrrw_a3,
      CPU_is_csrrw_a4;

// For |cpu$is_csrrwi.
logic CPU_is_csrrwi_a0,
      CPU_is_csrrwi_a1,
      CPU_is_csrrwi_a2,
      CPU_is_csrrwi_a3,
      CPU_is_csrrwi_a4;

// For |cpu$is_i_instr.
logic CPU_is_i_instr_a1;

// For |cpu$is_j_instr.
logic CPU_is_j_instr_a1;

// For |cpu$is_jal.
logic CPU_is_jal_a1,
      CPU_is_jal_a2,
      CPU_is_jal_a3,
      CPU_is_jal_a4;

// For |cpu$is_jalr.
logic CPU_is_jalr_a1,
      CPU_is_jalr_a2,
      CPU_is_jalr_a3,
      CPU_is_jalr_a4;

// For |cpu$is_jump.
logic CPU_is_jump_a1,
      CPU_is_jump_a2,
      CPU_is_jump_a3;

// For |cpu$is_lb.
logic CPU_is_lb_a0,
      CPU_is_lb_a1,
      CPU_is_lb_a2,
      CPU_is_lb_a3,
      CPU_is_lb_a4;

// For |cpu$is_lbu.
logic CPU_is_lbu_a0,
      CPU_is_lbu_a1,
      CPU_is_lbu_a2,
      CPU_is_lbu_a3,
      CPU_is_lbu_a4;

// For |cpu$is_lh.
logic CPU_is_lh_a0,
      CPU_is_lh_a1,
      CPU_is_lh_a2,
      CPU_is_lh_a3,
      CPU_is_lh_a4;

// For |cpu$is_lhu.
logic CPU_is_lhu_a0,
      CPU_is_lhu_a1,
      CPU_is_lhu_a2,
      CPU_is_lhu_a3,
      CPU_is_lhu_a4;

// For |cpu$is_load.
logic CPU_is_load_a1,
      CPU_is_load_a2,
      CPU_is_load_a3,
      CPU_is_load_a4;

// For |cpu$is_lui.
logic CPU_is_lui_a1,
      CPU_is_lui_a2,
      CPU_is_lui_a3,
      CPU_is_lui_a4;

// For |cpu$is_lw.
logic CPU_is_lw_a0,
      CPU_is_lw_a1,
      CPU_is_lw_a2,
      CPU_is_lw_a3,
      CPU_is_lw_a4;

// For |cpu$is_or.
logic CPU_is_or_a1,
      CPU_is_or_a2,
      CPU_is_or_a3,
      CPU_is_or_a4;

// For |cpu$is_ori.
logic CPU_is_ori_a1,
      CPU_is_ori_a2,
      CPU_is_ori_a3,
      CPU_is_ori_a4;

// For |cpu$is_r_instr.
logic CPU_is_r_instr_a1;

// For |cpu$is_s_instr.
logic CPU_is_s_instr_a1,
      CPU_is_s_instr_a2,
      CPU_is_s_instr_a3,
      CPU_is_s_instr_a4;

// For |cpu$is_sb.
logic CPU_is_sb_a1,
      CPU_is_sb_a2,
      CPU_is_sb_a3,
      CPU_is_sb_a4;

// For |cpu$is_sh.
logic CPU_is_sh_a1,
      CPU_is_sh_a2,
      CPU_is_sh_a3,
      CPU_is_sh_a4;

// For |cpu$is_sll.
logic CPU_is_sll_a1,
      CPU_is_sll_a2,
      CPU_is_sll_a3,
      CPU_is_sll_a4;

// For |cpu$is_slli.
logic CPU_is_slli_a1,
      CPU_is_slli_a2,
      CPU_is_slli_a3,
      CPU_is_slli_a4;

// For |cpu$is_slt.
logic CPU_is_slt_a1,
      CPU_is_slt_a2,
      CPU_is_slt_a3,
      CPU_is_slt_a4;

// For |cpu$is_slti.
logic CPU_is_slti_a1,
      CPU_is_slti_a2,
      CPU_is_slti_a3,
      CPU_is_slti_a4;

// For |cpu$is_sltiu.
logic CPU_is_sltiu_a1,
      CPU_is_sltiu_a2,
      CPU_is_sltiu_a3,
      CPU_is_sltiu_a4;

// For |cpu$is_sltu.
logic CPU_is_sltu_a1,
      CPU_is_sltu_a2,
      CPU_is_sltu_a3,
      CPU_is_sltu_a4;

// For |cpu$is_sra.
logic CPU_is_sra_a1,
      CPU_is_sra_a2,
      CPU_is_sra_a3,
      CPU_is_sra_a4;

// For |cpu$is_srai.
logic CPU_is_srai_a1,
      CPU_is_srai_a2,
      CPU_is_srai_a3,
      CPU_is_srai_a4;

// For |cpu$is_srl.
logic CPU_is_srl_a1,
      CPU_is_srl_a2,
      CPU_is_srl_a3,
      CPU_is_srl_a4;

// For |cpu$is_srli.
logic CPU_is_srli_a1,
      CPU_is_srli_a2,
      CPU_is_srli_a3,
      CPU_is_srli_a4;

// For |cpu$is_store.
logic CPU_is_store_a0,
      CPU_is_store_a1,
      CPU_is_store_a2,
      CPU_is_store_a3,
      CPU_is_store_a4;

// For |cpu$is_sub.
logic CPU_is_sub_a1,
      CPU_is_sub_a2,
      CPU_is_sub_a3,
      CPU_is_sub_a4;

// For |cpu$is_sw.
logic CPU_is_sw_a1,
      CPU_is_sw_a2,
      CPU_is_sw_a3,
      CPU_is_sw_a4;

// For |cpu$is_u_instr.
logic CPU_is_u_instr_a1;

// For |cpu$is_xor.
logic CPU_is_xor_a1,
      CPU_is_xor_a2,
      CPU_is_xor_a3,
      CPU_is_xor_a4;

// For |cpu$is_xori.
logic CPU_is_xori_a1,
      CPU_is_xori_a2,
      CPU_is_xori_a3,
      CPU_is_xori_a4;

// For |cpu$jalr_tgt_pc.
logic [31:0] CPU_jalr_tgt_pc_a2,
             CPU_jalr_tgt_pc_a3;

// For |cpu$ld_data.
logic [31:0] CPU_ld_data_a5;

// For |cpu$opcode.
logic [6:0] CPU_opcode_a1;

// For |cpu$pc.
logic [31:0] CPU_pc_a0,
             CPU_pc_a1,
             CPU_pc_a2,
             CPU_pc_a3,
             CPU_pc_a4;

// For |cpu$rd.
logic [4:0] CPU_rd_a1,
            CPU_rd_a2,
            CPU_rd_a3,
            CPU_rd_a4,
            CPU_rd_a5;

// For |cpu$rd_valid.
logic CPU_rd_valid_a1,
      CPU_rd_valid_a2,
      CPU_rd_valid_a3,
      CPU_rd_valid_a4;

// For |cpu$reset.
logic CPU_reset_a0,
      CPU_reset_a1,
      CPU_reset_a2,
      CPU_reset_a3,
      CPU_reset_a4;

// For |cpu$result.
logic [31:0] CPU_result_a3,
             CPU_result_a4;

// For |cpu$rf_rd_data1.
logic [31:0] CPU_rf_rd_data1_a2;

// For |cpu$rf_rd_data2.
logic [31:0] CPU_rf_rd_data2_a2;

// For |cpu$rf_rd_en1.
logic CPU_rf_rd_en1_a2;

// For |cpu$rf_rd_en2.
logic CPU_rf_rd_en2_a2;

// For |cpu$rf_rd_index1.
logic [4:0] CPU_rf_rd_index1_a2;

// For |cpu$rf_rd_index2.
logic [4:0] CPU_rf_rd_index2_a2;

// For |cpu$rf_wr_data.
logic [31:0] CPU_rf_wr_data_a3;

// For |cpu$rf_wr_en.
logic CPU_rf_wr_en_a3;

// For |cpu$rf_wr_index.
logic [4:0] CPU_rf_wr_index_a3;

// For |cpu$rs1.
logic [4:0] CPU_rs1_a1,
            CPU_rs1_a2,
            CPU_rs1_a3,
            CPU_rs1_a4;

// For |cpu$rs1_valid.
logic CPU_rs1_valid_a1,
      CPU_rs1_valid_a2,
      CPU_rs1_valid_a3,
      CPU_rs1_valid_a4;

// For |cpu$rs2.
logic [4:0] CPU_rs2_a1,
            CPU_rs2_a2,
            CPU_rs2_a3,
            CPU_rs2_a4;

// For |cpu$rs2_valid.
logic CPU_rs2_valid_a1,
      CPU_rs2_valid_a2,
      CPU_rs2_valid_a3,
      CPU_rs2_valid_a4;

// For |cpu$sltiu_result.
logic CPU_sltiu_result_a3;

// For |cpu$sltu_result.
logic CPU_sltu_result_a3;

// For |cpu$src1_value.
logic [31:0] CPU_src1_value_a2,
             CPU_src1_value_a3,
             CPU_src1_value_a4;

// For |cpu$src2_value.
logic [31:0] CPU_src2_value_a2,
             CPU_src2_value_a3,
             CPU_src2_value_a4;

// For |cpu$taken_br.
logic CPU_taken_br_a3;

// For |cpu$valid.
logic CPU_valid_a3,
      CPU_valid_a4;

// For |cpu$valid_jump.
logic CPU_valid_jump_a3,
      CPU_valid_jump_a4,
      CPU_valid_jump_a5;

// For |cpu$valid_load.
logic CPU_valid_load_a3,
      CPU_valid_load_a4,
      CPU_valid_load_a5;

// For |cpu$valid_taken_br.
logic CPU_valid_taken_br_a3,
      CPU_valid_taken_br_a4,
      CPU_valid_taken_br_a5;

// For |cpu/dmem$value.
logic [31:0] CPU_Dmem_value_a4 [15:0],
             CPU_Dmem_value_a5 [15:0];

// For |cpu/imem$instr.
logic [31:0] CPU_Imem_instr_a1 [9:0];

// For |cpu/xreg$value.
logic [31:0] CPU_Xreg_value_a3 [31:0],
             CPU_Xreg_value_a4 [31:0],
             CPU_Xreg_value_a5 [31:0];

// For |cpuviz$imm.
logic [31:0] CPUVIZ_imm_a4;

// For |cpuviz$is_add.
logic CPUVIZ_is_add_a4;

// For |cpuviz$is_addi.
logic CPUVIZ_is_addi_a4;

// For |cpuviz$is_and.
logic CPUVIZ_is_and_a4;

// For |cpuviz$is_andi.
logic CPUVIZ_is_andi_a4;

// For |cpuviz$is_auipc.
logic CPUVIZ_is_auipc_a4;

// For |cpuviz$is_beq.
logic CPUVIZ_is_beq_a4;

// For |cpuviz$is_bge.
logic CPUVIZ_is_bge_a4;

// For |cpuviz$is_bgeu.
logic CPUVIZ_is_bgeu_a4;

// For |cpuviz$is_blt.
logic CPUVIZ_is_blt_a4;

// For |cpuviz$is_bltu.
logic CPUVIZ_is_bltu_a4;

// For |cpuviz$is_bne.
logic CPUVIZ_is_bne_a4;

// For |cpuviz$is_csrrc.
logic CPUVIZ_is_csrrc_a4;

// For |cpuviz$is_csrrci.
logic CPUVIZ_is_csrrci_a4;

// For |cpuviz$is_csrrs.
logic CPUVIZ_is_csrrs_a4;

// For |cpuviz$is_csrrsi.
logic CPUVIZ_is_csrrsi_a4;

// For |cpuviz$is_csrrw.
logic CPUVIZ_is_csrrw_a4;

// For |cpuviz$is_csrrwi.
logic CPUVIZ_is_csrrwi_a4;

// For |cpuviz$is_jal.
logic CPUVIZ_is_jal_a4;

// For |cpuviz$is_jalr.
logic CPUVIZ_is_jalr_a4;

// For |cpuviz$is_lb.
logic CPUVIZ_is_lb_a4;

// For |cpuviz$is_lbu.
logic CPUVIZ_is_lbu_a4;

// For |cpuviz$is_lh.
logic CPUVIZ_is_lh_a4;

// For |cpuviz$is_lhu.
logic CPUVIZ_is_lhu_a4;

// For |cpuviz$is_load.
logic CPUVIZ_is_load_a4;

// For |cpuviz$is_lui.
logic CPUVIZ_is_lui_a4;

// For |cpuviz$is_lw.
logic CPUVIZ_is_lw_a4;

// For |cpuviz$is_or.
logic CPUVIZ_is_or_a4;

// For |cpuviz$is_ori.
logic CPUVIZ_is_ori_a4;

// For |cpuviz$is_sb.
logic CPUVIZ_is_sb_a4;

// For |cpuviz$is_sh.
logic CPUVIZ_is_sh_a4;

// For |cpuviz$is_sll.
logic CPUVIZ_is_sll_a4;

// For |cpuviz$is_slli.
logic CPUVIZ_is_slli_a4;

// For |cpuviz$is_slt.
logic CPUVIZ_is_slt_a4;

// For |cpuviz$is_slti.
logic CPUVIZ_is_slti_a4;

// For |cpuviz$is_sltiu.
logic CPUVIZ_is_sltiu_a4;

// For |cpuviz$is_sltu.
logic CPUVIZ_is_sltu_a4;

// For |cpuviz$is_sra.
logic CPUVIZ_is_sra_a4;

// For |cpuviz$is_srai.
logic CPUVIZ_is_srai_a4;

// For |cpuviz$is_srl.
logic CPUVIZ_is_srl_a4;

// For |cpuviz$is_srli.
logic CPUVIZ_is_srli_a4;

// For |cpuviz$is_store.
logic CPUVIZ_is_store_a4;

// For |cpuviz$is_sub.
logic CPUVIZ_is_sub_a4;

// For |cpuviz$is_sw.
logic CPUVIZ_is_sw_a4;

// For |cpuviz$is_xor.
logic CPUVIZ_is_xor_a4;

// For |cpuviz$is_xori.
logic CPUVIZ_is_xori_a4;

// For |cpuviz$mnemonic.
logic [10*8-1:0] CPUVIZ_mnemonic_a4;

// For |cpuviz$pc.
logic [31:0] CPUVIZ_pc_a4;

// For |cpuviz$rd.
logic [4:0] CPUVIZ_rd_a4;

// For |cpuviz$rd_valid.
logic CPUVIZ_rd_valid_a4;

// For |cpuviz$result.
logic [31:0] CPUVIZ_result_a4;

// For |cpuviz$rs1.
logic [4:0] CPUVIZ_rs1_a4;

// For |cpuviz$rs1_valid.
logic CPUVIZ_rs1_valid_a4;

// For |cpuviz$rs2.
logic [4:0] CPUVIZ_rs2_a4;

// For |cpuviz$rs2_valid.
logic CPUVIZ_rs2_valid_a4;

// For |cpuviz$src1_value.
logic [31:0] CPUVIZ_src1_value_a4;

// For |cpuviz$src2_value.
logic [31:0] CPUVIZ_src2_value_a4;

// For |cpuviz$valid.
logic CPUVIZ_valid_a4;

// For |cpuviz/defaults$dummy.
logic [0:0] CPUVIZ_Defaults_dummy_a0;

// For |cpuviz/defaults$imem_rd_addr.
logic [4-1:0] CPUVIZ_Defaults_imem_rd_addr_a0;

// For |cpuviz/defaults$imem_rd_en.
logic CPUVIZ_Defaults_imem_rd_en_a0;

// For |cpuviz/defaults$imm.
logic [31:0] CPUVIZ_Defaults_imm_a0;

// For |cpuviz/defaults$is_add.
logic CPUVIZ_Defaults_is_add_a0;

// For |cpuviz/defaults$is_addi.
logic CPUVIZ_Defaults_is_addi_a0;

// For |cpuviz/defaults$is_and.
logic CPUVIZ_Defaults_is_and_a0;

// For |cpuviz/defaults$is_andi.
logic CPUVIZ_Defaults_is_andi_a0;

// For |cpuviz/defaults$is_auipc.
logic CPUVIZ_Defaults_is_auipc_a0;

// For |cpuviz/defaults$is_beq.
logic CPUVIZ_Defaults_is_beq_a0;

// For |cpuviz/defaults$is_bge.
logic CPUVIZ_Defaults_is_bge_a0;

// For |cpuviz/defaults$is_bgeu.
logic CPUVIZ_Defaults_is_bgeu_a0;

// For |cpuviz/defaults$is_blt.
logic CPUVIZ_Defaults_is_blt_a0;

// For |cpuviz/defaults$is_bltu.
logic CPUVIZ_Defaults_is_bltu_a0;

// For |cpuviz/defaults$is_bne.
logic CPUVIZ_Defaults_is_bne_a0;

// For |cpuviz/defaults$is_csrrc.
logic CPUVIZ_Defaults_is_csrrc_a0;

// For |cpuviz/defaults$is_csrrci.
logic CPUVIZ_Defaults_is_csrrci_a0;

// For |cpuviz/defaults$is_csrrs.
logic CPUVIZ_Defaults_is_csrrs_a0;

// For |cpuviz/defaults$is_csrrsi.
logic CPUVIZ_Defaults_is_csrrsi_a0;

// For |cpuviz/defaults$is_csrrw.
logic CPUVIZ_Defaults_is_csrrw_a0;

// For |cpuviz/defaults$is_csrrwi.
logic CPUVIZ_Defaults_is_csrrwi_a0;

// For |cpuviz/defaults$is_jal.
logic CPUVIZ_Defaults_is_jal_a0;

// For |cpuviz/defaults$is_jalr.
logic CPUVIZ_Defaults_is_jalr_a0;

// For |cpuviz/defaults$is_lb.
logic CPUVIZ_Defaults_is_lb_a0;

// For |cpuviz/defaults$is_lbu.
logic CPUVIZ_Defaults_is_lbu_a0;

// For |cpuviz/defaults$is_lh.
logic CPUVIZ_Defaults_is_lh_a0;

// For |cpuviz/defaults$is_lhu.
logic CPUVIZ_Defaults_is_lhu_a0;

// For |cpuviz/defaults$is_load.
logic CPUVIZ_Defaults_is_load_a0;

// For |cpuviz/defaults$is_lui.
logic CPUVIZ_Defaults_is_lui_a0;

// For |cpuviz/defaults$is_lw.
logic CPUVIZ_Defaults_is_lw_a0;

// For |cpuviz/defaults$is_or.
logic CPUVIZ_Defaults_is_or_a0;

// For |cpuviz/defaults$is_ori.
logic CPUVIZ_Defaults_is_ori_a0;

// For |cpuviz/defaults$is_s_instr.
logic CPUVIZ_Defaults_is_s_instr_a0;

// For |cpuviz/defaults$is_sb.
logic CPUVIZ_Defaults_is_sb_a0;

// For |cpuviz/defaults$is_sh.
logic CPUVIZ_Defaults_is_sh_a0;

// For |cpuviz/defaults$is_sll.
logic CPUVIZ_Defaults_is_sll_a0;

// For |cpuviz/defaults$is_slli.
logic CPUVIZ_Defaults_is_slli_a0;

// For |cpuviz/defaults$is_slt.
logic CPUVIZ_Defaults_is_slt_a0;

// For |cpuviz/defaults$is_slti.
logic CPUVIZ_Defaults_is_slti_a0;

// For |cpuviz/defaults$is_sltiu.
logic CPUVIZ_Defaults_is_sltiu_a0;

// For |cpuviz/defaults$is_sltu.
logic CPUVIZ_Defaults_is_sltu_a0;

// For |cpuviz/defaults$is_sra.
logic CPUVIZ_Defaults_is_sra_a0;

// For |cpuviz/defaults$is_srai.
logic CPUVIZ_Defaults_is_srai_a0;

// For |cpuviz/defaults$is_srl.
logic CPUVIZ_Defaults_is_srl_a0;

// For |cpuviz/defaults$is_srli.
logic CPUVIZ_Defaults_is_srli_a0;

// For |cpuviz/defaults$is_store.
logic CPUVIZ_Defaults_is_store_a0;

// For |cpuviz/defaults$is_sub.
logic CPUVIZ_Defaults_is_sub_a0;

// For |cpuviz/defaults$is_sw.
logic CPUVIZ_Defaults_is_sw_a0;

// For |cpuviz/defaults$is_xor.
logic CPUVIZ_Defaults_is_xor_a0;

// For |cpuviz/defaults$is_xori.
logic CPUVIZ_Defaults_is_xori_a0;

// For |cpuviz/defaults$ld_data.
logic [31:0] CPUVIZ_Defaults_ld_data_a0;

// For |cpuviz/defaults$pc.
logic [31:0] CPUVIZ_Defaults_pc_a0;

// For |cpuviz/defaults$rd.
logic [4:0] CPUVIZ_Defaults_rd_a0;

// For |cpuviz/defaults$rd_valid.
logic CPUVIZ_Defaults_rd_valid_a0;

// For |cpuviz/defaults$result.
logic [31:0] CPUVIZ_Defaults_result_a0;

// For |cpuviz/defaults$rf_rd_en1.
logic CPUVIZ_Defaults_rf_rd_en1_a0;

// For |cpuviz/defaults$rf_rd_en2.
logic CPUVIZ_Defaults_rf_rd_en2_a0;

// For |cpuviz/defaults$rf_rd_index1.
logic [4:0] CPUVIZ_Defaults_rf_rd_index1_a0;

// For |cpuviz/defaults$rf_rd_index2.
logic [4:0] CPUVIZ_Defaults_rf_rd_index2_a0;

// For |cpuviz/defaults$rf_wr_data.
logic [31:0] CPUVIZ_Defaults_rf_wr_data_a0;

// For |cpuviz/defaults$rf_wr_en.
logic CPUVIZ_Defaults_rf_wr_en_a0;

// For |cpuviz/defaults$rf_wr_index.
logic [4:0] CPUVIZ_Defaults_rf_wr_index_a0;

// For |cpuviz/defaults$rs1.
logic [4:0] CPUVIZ_Defaults_rs1_a0;

// For |cpuviz/defaults$rs1_valid.
logic CPUVIZ_Defaults_rs1_valid_a0;

// For |cpuviz/defaults$rs2.
logic [4:0] CPUVIZ_Defaults_rs2_a0;

// For |cpuviz/defaults$rs2_valid.
logic CPUVIZ_Defaults_rs2_valid_a0;

// For |cpuviz/defaults$src1_value.
logic [31:0] CPUVIZ_Defaults_src1_value_a0;

// For |cpuviz/defaults$src2_value.
logic [31:0] CPUVIZ_Defaults_src2_value_a0;

// For |cpuviz/defaults$valid.
logic CPUVIZ_Defaults_valid_a0;


//
// Scope: |cpu
//

// Clock signals.
logic clkP_CPU_dmem_rd_en_a5 ;
logic clkP_CPU_rd_valid_a2 ;
logic clkP_CPU_rd_valid_a3 ;
logic clkP_CPU_rd_valid_a4 ;
logic clkP_CPU_rd_valid_a5 ;
logic clkP_CPU_rs1_valid_a2 ;
logic clkP_CPU_rs1_valid_a3 ;
logic clkP_CPU_rs1_valid_a4 ;
logic clkP_CPU_rs2_valid_a2 ;
logic clkP_CPU_rs2_valid_a3 ;
logic clkP_CPU_rs2_valid_a4 ;


generate


   //
   // Scope: |cpu
   //

      // For $br_tgt_pc.
      always_ff @(posedge clk) CPU_br_tgt_pc_a3[31:0] <= CPU_br_tgt_pc_a2[31:0];

      // For $dmem_rd_data.
      always_ff @(posedge clkP_CPU_dmem_rd_en_a5) CPU_dmem_rd_data_a5[31:0] <= CPU_dmem_rd_data_a4[31:0];

      // For $imem_rd_addr.
      always_ff @(posedge clk) CPU_imem_rd_addr_a1[31:0] <= CPU_imem_rd_addr_a0[31:0];

      // For $imem_rd_en.
      always_ff @(posedge clk) CPU_imem_rd_en_a1 <= CPU_imem_rd_en_a0;

      // For $imm.
      always_ff @(posedge clk) CPU_imm_a2[31:0] <= CPU_imm_a1[31:0];
      always_ff @(posedge clk) CPU_imm_a3[31:0] <= CPU_imm_a2[31:0];
      always_ff @(posedge clk) CPU_imm_a4[31:0] <= CPU_imm_a3[31:0];

      // For $inc_pc.
      always_ff @(posedge clk) CPU_inc_pc_a2[31:0] <= CPU_inc_pc_a1[31:0];
      always_ff @(posedge clk) CPU_inc_pc_a3[31:0] <= CPU_inc_pc_a2[31:0];

      // For $is_add.
      always_ff @(posedge clk) CPU_is_add_a2 <= CPU_is_add_a1;
      always_ff @(posedge clk) CPU_is_add_a3 <= CPU_is_add_a2;
      always_ff @(posedge clk) CPU_is_add_a4 <= CPU_is_add_a3;

      // For $is_addi.
      always_ff @(posedge clk) CPU_is_addi_a2 <= CPU_is_addi_a1;
      always_ff @(posedge clk) CPU_is_addi_a3 <= CPU_is_addi_a2;
      always_ff @(posedge clk) CPU_is_addi_a4 <= CPU_is_addi_a3;

      // For $is_and.
      always_ff @(posedge clk) CPU_is_and_a2 <= CPU_is_and_a1;
      always_ff @(posedge clk) CPU_is_and_a3 <= CPU_is_and_a2;
      always_ff @(posedge clk) CPU_is_and_a4 <= CPU_is_and_a3;

      // For $is_andi.
      always_ff @(posedge clk) CPU_is_andi_a2 <= CPU_is_andi_a1;
      always_ff @(posedge clk) CPU_is_andi_a3 <= CPU_is_andi_a2;
      always_ff @(posedge clk) CPU_is_andi_a4 <= CPU_is_andi_a3;

      // For $is_auipc.
      always_ff @(posedge clk) CPU_is_auipc_a2 <= CPU_is_auipc_a1;
      always_ff @(posedge clk) CPU_is_auipc_a3 <= CPU_is_auipc_a2;
      always_ff @(posedge clk) CPU_is_auipc_a4 <= CPU_is_auipc_a3;

      // For $is_beq.
      always_ff @(posedge clk) CPU_is_beq_a2 <= CPU_is_beq_a1;
      always_ff @(posedge clk) CPU_is_beq_a3 <= CPU_is_beq_a2;
      always_ff @(posedge clk) CPU_is_beq_a4 <= CPU_is_beq_a3;
      always_ff @(posedge clk) CPU_is_beq_a5 <= CPU_is_beq_a4;

      // For $is_bge.
      always_ff @(posedge clk) CPU_is_bge_a2 <= CPU_is_bge_a1;
      always_ff @(posedge clk) CPU_is_bge_a3 <= CPU_is_bge_a2;
      always_ff @(posedge clk) CPU_is_bge_a4 <= CPU_is_bge_a3;
      always_ff @(posedge clk) CPU_is_bge_a5 <= CPU_is_bge_a4;

      // For $is_bgeu.
      always_ff @(posedge clk) CPU_is_bgeu_a2 <= CPU_is_bgeu_a1;
      always_ff @(posedge clk) CPU_is_bgeu_a3 <= CPU_is_bgeu_a2;
      always_ff @(posedge clk) CPU_is_bgeu_a4 <= CPU_is_bgeu_a3;
      always_ff @(posedge clk) CPU_is_bgeu_a5 <= CPU_is_bgeu_a4;

      // For $is_blt.
      always_ff @(posedge clk) CPU_is_blt_a2 <= CPU_is_blt_a1;
      always_ff @(posedge clk) CPU_is_blt_a3 <= CPU_is_blt_a2;
      always_ff @(posedge clk) CPU_is_blt_a4 <= CPU_is_blt_a3;
      always_ff @(posedge clk) CPU_is_blt_a5 <= CPU_is_blt_a4;

      // For $is_bltu.
      always_ff @(posedge clk) CPU_is_bltu_a2 <= CPU_is_bltu_a1;
      always_ff @(posedge clk) CPU_is_bltu_a3 <= CPU_is_bltu_a2;
      always_ff @(posedge clk) CPU_is_bltu_a4 <= CPU_is_bltu_a3;
      always_ff @(posedge clk) CPU_is_bltu_a5 <= CPU_is_bltu_a4;

      // For $is_bne.
      always_ff @(posedge clk) CPU_is_bne_a2 <= CPU_is_bne_a1;
      always_ff @(posedge clk) CPU_is_bne_a3 <= CPU_is_bne_a2;
      always_ff @(posedge clk) CPU_is_bne_a4 <= CPU_is_bne_a3;
      always_ff @(posedge clk) CPU_is_bne_a5 <= CPU_is_bne_a4;

      // For $is_csrrc.
      always_ff @(posedge clk) CPU_is_csrrc_a1 <= CPU_is_csrrc_a0;
      always_ff @(posedge clk) CPU_is_csrrc_a2 <= CPU_is_csrrc_a1;
      always_ff @(posedge clk) CPU_is_csrrc_a3 <= CPU_is_csrrc_a2;
      always_ff @(posedge clk) CPU_is_csrrc_a4 <= CPU_is_csrrc_a3;

      // For $is_csrrci.
      always_ff @(posedge clk) CPU_is_csrrci_a1 <= CPU_is_csrrci_a0;
      always_ff @(posedge clk) CPU_is_csrrci_a2 <= CPU_is_csrrci_a1;
      always_ff @(posedge clk) CPU_is_csrrci_a3 <= CPU_is_csrrci_a2;
      always_ff @(posedge clk) CPU_is_csrrci_a4 <= CPU_is_csrrci_a3;

      // For $is_csrrs.
      always_ff @(posedge clk) CPU_is_csrrs_a1 <= CPU_is_csrrs_a0;
      always_ff @(posedge clk) CPU_is_csrrs_a2 <= CPU_is_csrrs_a1;
      always_ff @(posedge clk) CPU_is_csrrs_a3 <= CPU_is_csrrs_a2;
      always_ff @(posedge clk) CPU_is_csrrs_a4 <= CPU_is_csrrs_a3;

      // For $is_csrrsi.
      always_ff @(posedge clk) CPU_is_csrrsi_a1 <= CPU_is_csrrsi_a0;
      always_ff @(posedge clk) CPU_is_csrrsi_a2 <= CPU_is_csrrsi_a1;
      always_ff @(posedge clk) CPU_is_csrrsi_a3 <= CPU_is_csrrsi_a2;
      always_ff @(posedge clk) CPU_is_csrrsi_a4 <= CPU_is_csrrsi_a3;

      // For $is_csrrw.
      always_ff @(posedge clk) CPU_is_csrrw_a1 <= CPU_is_csrrw_a0;
      always_ff @(posedge clk) CPU_is_csrrw_a2 <= CPU_is_csrrw_a1;
      always_ff @(posedge clk) CPU_is_csrrw_a3 <= CPU_is_csrrw_a2;
      always_ff @(posedge clk) CPU_is_csrrw_a4 <= CPU_is_csrrw_a3;

      // For $is_csrrwi.
      always_ff @(posedge clk) CPU_is_csrrwi_a1 <= CPU_is_csrrwi_a0;
      always_ff @(posedge clk) CPU_is_csrrwi_a2 <= CPU_is_csrrwi_a1;
      always_ff @(posedge clk) CPU_is_csrrwi_a3 <= CPU_is_csrrwi_a2;
      always_ff @(posedge clk) CPU_is_csrrwi_a4 <= CPU_is_csrrwi_a3;

      // For $is_jal.
      always_ff @(posedge clk) CPU_is_jal_a2 <= CPU_is_jal_a1;
      always_ff @(posedge clk) CPU_is_jal_a3 <= CPU_is_jal_a2;
      always_ff @(posedge clk) CPU_is_jal_a4 <= CPU_is_jal_a3;

      // For $is_jalr.
      always_ff @(posedge clk) CPU_is_jalr_a2 <= CPU_is_jalr_a1;
      always_ff @(posedge clk) CPU_is_jalr_a3 <= CPU_is_jalr_a2;
      always_ff @(posedge clk) CPU_is_jalr_a4 <= CPU_is_jalr_a3;

      // For $is_jump.
      always_ff @(posedge clk) CPU_is_jump_a2 <= CPU_is_jump_a1;
      always_ff @(posedge clk) CPU_is_jump_a3 <= CPU_is_jump_a2;

      // For $is_lb.
      always_ff @(posedge clk) CPU_is_lb_a1 <= CPU_is_lb_a0;
      always_ff @(posedge clk) CPU_is_lb_a2 <= CPU_is_lb_a1;
      always_ff @(posedge clk) CPU_is_lb_a3 <= CPU_is_lb_a2;
      always_ff @(posedge clk) CPU_is_lb_a4 <= CPU_is_lb_a3;

      // For $is_lbu.
      always_ff @(posedge clk) CPU_is_lbu_a1 <= CPU_is_lbu_a0;
      always_ff @(posedge clk) CPU_is_lbu_a2 <= CPU_is_lbu_a1;
      always_ff @(posedge clk) CPU_is_lbu_a3 <= CPU_is_lbu_a2;
      always_ff @(posedge clk) CPU_is_lbu_a4 <= CPU_is_lbu_a3;

      // For $is_lh.
      always_ff @(posedge clk) CPU_is_lh_a1 <= CPU_is_lh_a0;
      always_ff @(posedge clk) CPU_is_lh_a2 <= CPU_is_lh_a1;
      always_ff @(posedge clk) CPU_is_lh_a3 <= CPU_is_lh_a2;
      always_ff @(posedge clk) CPU_is_lh_a4 <= CPU_is_lh_a3;

      // For $is_lhu.
      always_ff @(posedge clk) CPU_is_lhu_a1 <= CPU_is_lhu_a0;
      always_ff @(posedge clk) CPU_is_lhu_a2 <= CPU_is_lhu_a1;
      always_ff @(posedge clk) CPU_is_lhu_a3 <= CPU_is_lhu_a2;
      always_ff @(posedge clk) CPU_is_lhu_a4 <= CPU_is_lhu_a3;

      // For $is_load.
      always_ff @(posedge clk) CPU_is_load_a2 <= CPU_is_load_a1;
      always_ff @(posedge clk) CPU_is_load_a3 <= CPU_is_load_a2;
      always_ff @(posedge clk) CPU_is_load_a4 <= CPU_is_load_a3;

      // For $is_lui.
      always_ff @(posedge clk) CPU_is_lui_a2 <= CPU_is_lui_a1;
      always_ff @(posedge clk) CPU_is_lui_a3 <= CPU_is_lui_a2;
      always_ff @(posedge clk) CPU_is_lui_a4 <= CPU_is_lui_a3;

      // For $is_lw.
      always_ff @(posedge clk) CPU_is_lw_a1 <= CPU_is_lw_a0;
      always_ff @(posedge clk) CPU_is_lw_a2 <= CPU_is_lw_a1;
      always_ff @(posedge clk) CPU_is_lw_a3 <= CPU_is_lw_a2;
      always_ff @(posedge clk) CPU_is_lw_a4 <= CPU_is_lw_a3;

      // For $is_or.
      always_ff @(posedge clk) CPU_is_or_a2 <= CPU_is_or_a1;
      always_ff @(posedge clk) CPU_is_or_a3 <= CPU_is_or_a2;
      always_ff @(posedge clk) CPU_is_or_a4 <= CPU_is_or_a3;

      // For $is_ori.
      always_ff @(posedge clk) CPU_is_ori_a2 <= CPU_is_ori_a1;
      always_ff @(posedge clk) CPU_is_ori_a3 <= CPU_is_ori_a2;
      always_ff @(posedge clk) CPU_is_ori_a4 <= CPU_is_ori_a3;

      // For $is_s_instr.
      always_ff @(posedge clk) CPU_is_s_instr_a2 <= CPU_is_s_instr_a1;
      always_ff @(posedge clk) CPU_is_s_instr_a3 <= CPU_is_s_instr_a2;
      always_ff @(posedge clk) CPU_is_s_instr_a4 <= CPU_is_s_instr_a3;

      // For $is_sb.
      always_ff @(posedge clk) CPU_is_sb_a2 <= CPU_is_sb_a1;
      always_ff @(posedge clk) CPU_is_sb_a3 <= CPU_is_sb_a2;
      always_ff @(posedge clk) CPU_is_sb_a4 <= CPU_is_sb_a3;

      // For $is_sh.
      always_ff @(posedge clk) CPU_is_sh_a2 <= CPU_is_sh_a1;
      always_ff @(posedge clk) CPU_is_sh_a3 <= CPU_is_sh_a2;
      always_ff @(posedge clk) CPU_is_sh_a4 <= CPU_is_sh_a3;

      // For $is_sll.
      always_ff @(posedge clk) CPU_is_sll_a2 <= CPU_is_sll_a1;
      always_ff @(posedge clk) CPU_is_sll_a3 <= CPU_is_sll_a2;
      always_ff @(posedge clk) CPU_is_sll_a4 <= CPU_is_sll_a3;

      // For $is_slli.
      always_ff @(posedge clk) CPU_is_slli_a2 <= CPU_is_slli_a1;
      always_ff @(posedge clk) CPU_is_slli_a3 <= CPU_is_slli_a2;
      always_ff @(posedge clk) CPU_is_slli_a4 <= CPU_is_slli_a3;

      // For $is_slt.
      always_ff @(posedge clk) CPU_is_slt_a2 <= CPU_is_slt_a1;
      always_ff @(posedge clk) CPU_is_slt_a3 <= CPU_is_slt_a2;
      always_ff @(posedge clk) CPU_is_slt_a4 <= CPU_is_slt_a3;

      // For $is_slti.
      always_ff @(posedge clk) CPU_is_slti_a2 <= CPU_is_slti_a1;
      always_ff @(posedge clk) CPU_is_slti_a3 <= CPU_is_slti_a2;
      always_ff @(posedge clk) CPU_is_slti_a4 <= CPU_is_slti_a3;

      // For $is_sltiu.
      always_ff @(posedge clk) CPU_is_sltiu_a2 <= CPU_is_sltiu_a1;
      always_ff @(posedge clk) CPU_is_sltiu_a3 <= CPU_is_sltiu_a2;
      always_ff @(posedge clk) CPU_is_sltiu_a4 <= CPU_is_sltiu_a3;

      // For $is_sltu.
      always_ff @(posedge clk) CPU_is_sltu_a2 <= CPU_is_sltu_a1;
      always_ff @(posedge clk) CPU_is_sltu_a3 <= CPU_is_sltu_a2;
      always_ff @(posedge clk) CPU_is_sltu_a4 <= CPU_is_sltu_a3;

      // For $is_sra.
      always_ff @(posedge clk) CPU_is_sra_a2 <= CPU_is_sra_a1;
      always_ff @(posedge clk) CPU_is_sra_a3 <= CPU_is_sra_a2;
      always_ff @(posedge clk) CPU_is_sra_a4 <= CPU_is_sra_a3;

      // For $is_srai.
      always_ff @(posedge clk) CPU_is_srai_a2 <= CPU_is_srai_a1;
      always_ff @(posedge clk) CPU_is_srai_a3 <= CPU_is_srai_a2;
      always_ff @(posedge clk) CPU_is_srai_a4 <= CPU_is_srai_a3;

      // For $is_srl.
      always_ff @(posedge clk) CPU_is_srl_a2 <= CPU_is_srl_a1;
      always_ff @(posedge clk) CPU_is_srl_a3 <= CPU_is_srl_a2;
      always_ff @(posedge clk) CPU_is_srl_a4 <= CPU_is_srl_a3;

      // For $is_srli.
      always_ff @(posedge clk) CPU_is_srli_a2 <= CPU_is_srli_a1;
      always_ff @(posedge clk) CPU_is_srli_a3 <= CPU_is_srli_a2;
      always_ff @(posedge clk) CPU_is_srli_a4 <= CPU_is_srli_a3;

      // For $is_store.
      always_ff @(posedge clk) CPU_is_store_a1 <= CPU_is_store_a0;
      always_ff @(posedge clk) CPU_is_store_a2 <= CPU_is_store_a1;
      always_ff @(posedge clk) CPU_is_store_a3 <= CPU_is_store_a2;
      always_ff @(posedge clk) CPU_is_store_a4 <= CPU_is_store_a3;

      // For $is_sub.
      always_ff @(posedge clk) CPU_is_sub_a2 <= CPU_is_sub_a1;
      always_ff @(posedge clk) CPU_is_sub_a3 <= CPU_is_sub_a2;
      always_ff @(posedge clk) CPU_is_sub_a4 <= CPU_is_sub_a3;

      // For $is_sw.
      always_ff @(posedge clk) CPU_is_sw_a2 <= CPU_is_sw_a1;
      always_ff @(posedge clk) CPU_is_sw_a3 <= CPU_is_sw_a2;
      always_ff @(posedge clk) CPU_is_sw_a4 <= CPU_is_sw_a3;

      // For $is_xor.
      always_ff @(posedge clk) CPU_is_xor_a2 <= CPU_is_xor_a1;
      always_ff @(posedge clk) CPU_is_xor_a3 <= CPU_is_xor_a2;
      always_ff @(posedge clk) CPU_is_xor_a4 <= CPU_is_xor_a3;

      // For $is_xori.
      always_ff @(posedge clk) CPU_is_xori_a2 <= CPU_is_xori_a1;
      always_ff @(posedge clk) CPU_is_xori_a3 <= CPU_is_xori_a2;
      always_ff @(posedge clk) CPU_is_xori_a4 <= CPU_is_xori_a3;

      // For $jalr_tgt_pc.
      always_ff @(posedge clk) CPU_jalr_tgt_pc_a3[31:0] <= CPU_jalr_tgt_pc_a2[31:0];

      // For $pc.
      always_ff @(posedge clk) CPU_pc_a1[31:0] <= CPU_pc_a0[31:0];
      always_ff @(posedge clk) CPU_pc_a2[31:0] <= CPU_pc_a1[31:0];
      always_ff @(posedge clk) CPU_pc_a3[31:0] <= CPU_pc_a2[31:0];
      always_ff @(posedge clk) CPU_pc_a4[31:0] <= CPU_pc_a3[31:0];

      // For $rd.
      always_ff @(posedge clkP_CPU_rd_valid_a2) CPU_rd_a2[4:0] <= CPU_rd_a1[4:0];
      always_ff @(posedge clkP_CPU_rd_valid_a3) CPU_rd_a3[4:0] <= CPU_rd_a2[4:0];
      always_ff @(posedge clkP_CPU_rd_valid_a4) CPU_rd_a4[4:0] <= CPU_rd_a3[4:0];
      always_ff @(posedge clkP_CPU_rd_valid_a5) CPU_rd_a5[4:0] <= CPU_rd_a4[4:0];

      // For $rd_valid.
      always_ff @(posedge clk) CPU_rd_valid_a2 <= CPU_rd_valid_a1;
      always_ff @(posedge clk) CPU_rd_valid_a3 <= CPU_rd_valid_a2;
      always_ff @(posedge clk) CPU_rd_valid_a4 <= CPU_rd_valid_a3;

      // For $reset.
      always_ff @(posedge clk) CPU_reset_a1 <= CPU_reset_a0;
      always_ff @(posedge clk) CPU_reset_a2 <= CPU_reset_a1;
      always_ff @(posedge clk) CPU_reset_a3 <= CPU_reset_a2;
      always_ff @(posedge clk) CPU_reset_a4 <= CPU_reset_a3;

      // For $result.
      always_ff @(posedge clk) CPU_result_a4[31:0] <= CPU_result_a3[31:0];

      // For $rs1.
      always_ff @(posedge clkP_CPU_rs1_valid_a2) CPU_rs1_a2[4:0] <= CPU_rs1_a1[4:0];
      always_ff @(posedge clkP_CPU_rs1_valid_a3) CPU_rs1_a3[4:0] <= CPU_rs1_a2[4:0];
      always_ff @(posedge clkP_CPU_rs1_valid_a4) CPU_rs1_a4[4:0] <= CPU_rs1_a3[4:0];

      // For $rs1_valid.
      always_ff @(posedge clk) CPU_rs1_valid_a2 <= CPU_rs1_valid_a1;
      always_ff @(posedge clk) CPU_rs1_valid_a3 <= CPU_rs1_valid_a2;
      always_ff @(posedge clk) CPU_rs1_valid_a4 <= CPU_rs1_valid_a3;

      // For $rs2.
      always_ff @(posedge clkP_CPU_rs2_valid_a2) CPU_rs2_a2[4:0] <= CPU_rs2_a1[4:0];
      always_ff @(posedge clkP_CPU_rs2_valid_a3) CPU_rs2_a3[4:0] <= CPU_rs2_a2[4:0];
      always_ff @(posedge clkP_CPU_rs2_valid_a4) CPU_rs2_a4[4:0] <= CPU_rs2_a3[4:0];

      // For $rs2_valid.
      always_ff @(posedge clk) CPU_rs2_valid_a2 <= CPU_rs2_valid_a1;
      always_ff @(posedge clk) CPU_rs2_valid_a3 <= CPU_rs2_valid_a2;
      always_ff @(posedge clk) CPU_rs2_valid_a4 <= CPU_rs2_valid_a3;

      // For $src1_value.
      always_ff @(posedge clk) CPU_src1_value_a3[31:0] <= CPU_src1_value_a2[31:0];
      always_ff @(posedge clk) CPU_src1_value_a4[31:0] <= CPU_src1_value_a3[31:0];

      // For $src2_value.
      always_ff @(posedge clk) CPU_src2_value_a3[31:0] <= CPU_src2_value_a2[31:0];
      always_ff @(posedge clk) CPU_src2_value_a4[31:0] <= CPU_src2_value_a3[31:0];

      // For $valid.
      always_ff @(posedge clk) CPU_valid_a4 <= CPU_valid_a3;

      // For $valid_jump.
      always_ff @(posedge clk) CPU_valid_jump_a4 <= CPU_valid_jump_a3;
      always_ff @(posedge clk) CPU_valid_jump_a5 <= CPU_valid_jump_a4;

      // For $valid_load.
      always_ff @(posedge clk) CPU_valid_load_a4 <= CPU_valid_load_a3;
      always_ff @(posedge clk) CPU_valid_load_a5 <= CPU_valid_load_a4;

      // For $valid_taken_br.
      always_ff @(posedge clk) CPU_valid_taken_br_a4 <= CPU_valid_taken_br_a3;
      always_ff @(posedge clk) CPU_valid_taken_br_a5 <= CPU_valid_taken_br_a4;


      //
      // Scope: /dmem[15:0]
      //
      for (dmem = 0; dmem <= 15; dmem++) begin : L1gen_CPU_Dmem
         // For $dummy.
         always_ff @(posedge clk) L1b_CPU_Dmem[dmem].L1_dummy_a1[0:0] <= L1b_CPU_Dmem[dmem].L1_dummy_a0[0:0];
         always_ff @(posedge clk) L1b_CPU_Dmem[dmem].L1_dummy_a2[0:0] <= L1b_CPU_Dmem[dmem].L1_dummy_a1[0:0];
         always_ff @(posedge clk) L1b_CPU_Dmem[dmem].L1_dummy_a3[0:0] <= L1b_CPU_Dmem[dmem].L1_dummy_a2[0:0];
         always_ff @(posedge clk) L1b_CPU_Dmem[dmem].L1_dummy_a4[0:0] <= L1b_CPU_Dmem[dmem].L1_dummy_a3[0:0];

         // For $value.
         always_ff @(posedge clk) CPU_Dmem_value_a5[dmem][31:0] <= CPU_Dmem_value_a4[dmem][31:0];

      end

      //
      // Scope: /xreg[31:0]
      //
      for (xreg = 0; xreg <= 31; xreg++) begin : L1gen_CPU_Xreg
         // For $dummy.
         always_ff @(posedge clk) L1b_CPU_Xreg[xreg].L1_dummy_a1[0:0] <= L1b_CPU_Xreg[xreg].L1_dummy_a0[0:0];
         always_ff @(posedge clk) L1b_CPU_Xreg[xreg].L1_dummy_a2[0:0] <= L1b_CPU_Xreg[xreg].L1_dummy_a1[0:0];
         always_ff @(posedge clk) L1b_CPU_Xreg[xreg].L1_dummy_a3[0:0] <= L1b_CPU_Xreg[xreg].L1_dummy_a2[0:0];
         always_ff @(posedge clk) L1b_CPU_Xreg[xreg].L1_dummy_a4[0:0] <= L1b_CPU_Xreg[xreg].L1_dummy_a3[0:0];

         // For $value.
         always_ff @(posedge clk) CPU_Xreg_value_a4[xreg][31:0] <= CPU_Xreg_value_a3[xreg][31:0];
         always_ff @(posedge clk) CPU_Xreg_value_a5[xreg][31:0] <= CPU_Xreg_value_a4[xreg][31:0];

         // For $wr.
         always_ff @(posedge clk) L1_CPU_Xreg[xreg].L1_wr_a4 <= L1_CPU_Xreg[xreg].L1_wr_a3;

      end


   //
   // Scope: |cpuviz
   //


      //
      // Scope: /dmem[15:0]
      //
      for (dmem = 0; dmem <= 15; dmem++) begin : L1gen_CPUVIZ_Dmem
         // For $value.
         always_ff @(posedge clk) L1_CPUVIZ_Dmem[dmem].L1_value_a5[31:0] <= L1_CPUVIZ_Dmem[dmem].L1_value_a4[31:0];

      end

      //
      // Scope: /xreg[31:0]
      //
      for (xreg = 0; xreg <= 31; xreg++) begin : L1gen_CPUVIZ_Xreg
         // For $value.
         always_ff @(posedge clk) L1_CPUVIZ_Xreg[xreg].L1_value_a5[31:0] <= L1_CPUVIZ_Xreg[xreg].L1_value_a4[31:0];

      end



endgenerate



//
// Gated clocks.
//

generate



   //
   // Scope: |cpu
   //

      clk_gate gen_clkP_CPU_dmem_rd_en_a5(clkP_CPU_dmem_rd_en_a5, clk, 1'b1, CPU_dmem_rd_en_a4, 1'b0);
      clk_gate gen_clkP_CPU_rd_valid_a2(clkP_CPU_rd_valid_a2, clk, 1'b1, CPU_rd_valid_a1, 1'b0);
      clk_gate gen_clkP_CPU_rd_valid_a3(clkP_CPU_rd_valid_a3, clk, 1'b1, CPU_rd_valid_a2, 1'b0);
      clk_gate gen_clkP_CPU_rd_valid_a4(clkP_CPU_rd_valid_a4, clk, 1'b1, CPU_rd_valid_a3, 1'b0);
      clk_gate gen_clkP_CPU_rd_valid_a5(clkP_CPU_rd_valid_a5, clk, 1'b1, CPU_rd_valid_a4, 1'b0);
      clk_gate gen_clkP_CPU_rs1_valid_a2(clkP_CPU_rs1_valid_a2, clk, 1'b1, CPU_rs1_valid_a1, 1'b0);
      clk_gate gen_clkP_CPU_rs1_valid_a3(clkP_CPU_rs1_valid_a3, clk, 1'b1, CPU_rs1_valid_a2, 1'b0);
      clk_gate gen_clkP_CPU_rs1_valid_a4(clkP_CPU_rs1_valid_a4, clk, 1'b1, CPU_rs1_valid_a3, 1'b0);
      clk_gate gen_clkP_CPU_rs2_valid_a2(clkP_CPU_rs2_valid_a2, clk, 1'b1, CPU_rs2_valid_a1, 1'b0);
      clk_gate gen_clkP_CPU_rs2_valid_a3(clkP_CPU_rs2_valid_a3, clk, 1'b1, CPU_rs2_valid_a2, 1'b0);
      clk_gate gen_clkP_CPU_rs2_valid_a4(clkP_CPU_rs2_valid_a4, clk, 1'b1, CPU_rs2_valid_a3, 1'b0);



endgenerate



generate   // This is awkward, but we need to go into 'generate' context in the line that `includes the declarations file.
