#include "ngspice/cm.h"
extern void cm_i2c_master_top(Mif_Private_t *);
/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_i2c_master_top.h"

        
void cm_i2c_master_top(Mif_Private_t *mif_private) 
{
	Digital_State_t *_op_wb_dat_o, *_op_wb_dat_o_old;
	Digital_State_t *_op_wb_ack_o, *_op_wb_ack_o_old;
	Digital_State_t *_op_wb_inta_o, *_op_wb_inta_o_old;
	Digital_State_t *_op_scl_pad_o, *_op_scl_pad_o_old;
	Digital_State_t *_op_scl_padoen_o, *_op_scl_padoen_o_old;
	Digital_State_t *_op_sda_pad_o, *_op_sda_pad_o_old;
	Digital_State_t *_op_sda_padoen_o, *_op_sda_padoen_o_old;

    static int inst_count=0;
    int count=0;
        
    if(mif_private->circuit.init)
    {   
        inst_count++;
        mif_private->param[0]->element[0].rvalue=inst_count;
        fooi2c_master_top(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_wb_clk_i=mif_private->conn[0]->size;

        port_wb_rst_i=mif_private->conn[1]->size;

        port_arst_i=mif_private->conn[2]->size;

        port_wb_adr_i=mif_private->conn[3]->size;

        port_wb_dat_i=mif_private->conn[4]->size;

        port_wb_we_i=mif_private->conn[5]->size;

        port_wb_stb_i=mif_private->conn[6]->size;

        port_wb_cyc_i=mif_private->conn[7]->size;

        port_scl_pad_i=mif_private->conn[8]->size;

        port_sda_pad_i=mif_private->conn[9]->size;

        port_wb_dat_o=mif_private->conn[10]->size;

        port_wb_ack_o=mif_private->conn[11]->size;

        port_wb_inta_o=mif_private->conn[12]->size;

        port_scl_pad_o=mif_private->conn[13]->size;

        port_scl_padoen_o=mif_private->conn[14]->size;

        port_sda_pad_o=mif_private->conn[15]->size;

        port_sda_padoen_o=mif_private->conn[16]->size;
		cm_event_alloc(0,8*sizeof(Digital_State_t));
		cm_event_alloc(1,1*sizeof(Digital_State_t));
		cm_event_alloc(2,1*sizeof(Digital_State_t));
		cm_event_alloc(3,1*sizeof(Digital_State_t));
		cm_event_alloc(4,1*sizeof(Digital_State_t));
		cm_event_alloc(5,1*sizeof(Digital_State_t));
		cm_event_alloc(6,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
		{
			mif_private->conn[0]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
		{
			mif_private->conn[1]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
		{
			mif_private->conn[2]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
		{
			mif_private->conn[3]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
		{
			mif_private->conn[4]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
		{
			mif_private->conn[5]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
		{
			mif_private->conn[6]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
		{
			mif_private->conn[7]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
		{
			mif_private->conn[8]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[9]->size;Ii++)
		{
			mif_private->conn[9]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}

		/*Retrieve Storage for output*/
		_op_wb_dat_o = _op_wb_dat_o_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_wb_ack_o = _op_wb_ack_o_old = (Digital_State_t *) cm_event_get_ptr(1,0);
		_op_wb_inta_o = _op_wb_inta_o_old = (Digital_State_t *) cm_event_get_ptr(2,0);
		_op_scl_pad_o = _op_scl_pad_o_old = (Digital_State_t *) cm_event_get_ptr(3,0);
		_op_scl_padoen_o = _op_scl_padoen_o_old = (Digital_State_t *) cm_event_get_ptr(4,0);
		_op_sda_pad_o = _op_sda_pad_o_old = (Digital_State_t *) cm_event_get_ptr(5,0);
		_op_sda_padoen_o = _op_sda_padoen_o_old = (Digital_State_t *) cm_event_get_ptr(6,0);


	}
	else
	{
		_op_wb_dat_o = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_wb_dat_o_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_wb_ack_o = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_wb_ack_o_old = (Digital_State_t *) cm_event_get_ptr(1,2);
		_op_wb_inta_o = (Digital_State_t *) cm_event_get_ptr(2,2);
		_op_wb_inta_o_old = (Digital_State_t *) cm_event_get_ptr(2,3);
		_op_scl_pad_o = (Digital_State_t *) cm_event_get_ptr(3,3);
		_op_scl_pad_o_old = (Digital_State_t *) cm_event_get_ptr(3,4);
		_op_scl_padoen_o = (Digital_State_t *) cm_event_get_ptr(4,4);
		_op_scl_padoen_o_old = (Digital_State_t *) cm_event_get_ptr(4,5);
		_op_sda_pad_o = (Digital_State_t *) cm_event_get_ptr(5,5);
		_op_sda_pad_o_old = (Digital_State_t *) cm_event_get_ptr(5,6);
		_op_sda_padoen_o = (Digital_State_t *) cm_event_get_ptr(6,6);
		_op_sda_padoen_o_old = (Digital_State_t *) cm_event_get_ptr(6,7);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)mif_private->param[0]->element[0].rvalue;

    for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[0]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_wb_clk_i[Ii]=0;            }
        else
        {
            temp_wb_clk_i[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[1]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_wb_rst_i[Ii]=0;            }
        else
        {
            temp_wb_rst_i[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[2]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_arst_i[Ii]=0;            }
        else
        {
            temp_arst_i[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[3]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_wb_adr_i[Ii]=0;            }
        else
        {
            temp_wb_adr_i[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[4]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_wb_dat_i[Ii]=0;            }
        else
        {
            temp_wb_dat_i[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[5]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_wb_we_i[Ii]=0;            }
        else
        {
            temp_wb_we_i[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[6]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_wb_stb_i[Ii]=0;            }
        else
        {
            temp_wb_stb_i[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[7]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_wb_cyc_i[Ii]=0;            }
        else
        {
            temp_wb_cyc_i[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[8]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_scl_pad_i[Ii]=0;            }
        else
        {
            temp_scl_pad_i[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[9]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[9]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_sda_pad_i[Ii]=0;            }
        else
        {
            temp_sda_pad_i[Ii]=1;
        }
            }
	fooi2c_master_top(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[10]->size;Ii++)
    {
        if(temp_wb_dat_o[Ii]==0)
        {
            _op_wb_dat_o[Ii]=ZERO;
            }
        else if(temp_wb_dat_o[Ii]==1)
        {
            _op_wb_dat_o[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->state = _op_wb_dat_o[Ii];
            }
        else if(_op_wb_dat_o[Ii] != _op_wb_dat_o_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->state = _op_wb_dat_o[Ii];
            mif_private->conn[10]->port[Ii]->delay = ((_op_wb_dat_o[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[10]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[11]->size;Ii++)
    {
        if(temp_wb_ack_o[Ii]==0)
        {
            _op_wb_ack_o[Ii]=ZERO;
            }
        else if(temp_wb_ack_o[Ii]==1)
        {
            _op_wb_ack_o[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->state = _op_wb_ack_o[Ii];
            }
        else if(_op_wb_ack_o[Ii] != _op_wb_ack_o_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->state = _op_wb_ack_o[Ii];
            mif_private->conn[11]->port[Ii]->delay = ((_op_wb_ack_o[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[11]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[12]->size;Ii++)
    {
        if(temp_wb_inta_o[Ii]==0)
        {
            _op_wb_inta_o[Ii]=ZERO;
            }
        else if(temp_wb_inta_o[Ii]==1)
        {
            _op_wb_inta_o[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->state = _op_wb_inta_o[Ii];
            }
        else if(_op_wb_inta_o[Ii] != _op_wb_inta_o_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->state = _op_wb_inta_o[Ii];
            mif_private->conn[12]->port[Ii]->delay = ((_op_wb_inta_o[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[12]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[13]->size;Ii++)
    {
        if(temp_scl_pad_o[Ii]==0)
        {
            _op_scl_pad_o[Ii]=ZERO;
            }
        else if(temp_scl_pad_o[Ii]==1)
        {
            _op_scl_pad_o[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[13]->port[Ii]->output.pvalue))->state = _op_scl_pad_o[Ii];
            }
        else if(_op_scl_pad_o[Ii] != _op_scl_pad_o_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[13]->port[Ii]->output.pvalue))->state = _op_scl_pad_o[Ii];
            mif_private->conn[13]->port[Ii]->delay = ((_op_scl_pad_o[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[13]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[13]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[14]->size;Ii++)
    {
        if(temp_scl_padoen_o[Ii]==0)
        {
            _op_scl_padoen_o[Ii]=ZERO;
            }
        else if(temp_scl_padoen_o[Ii]==1)
        {
            _op_scl_padoen_o[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[14]->port[Ii]->output.pvalue))->state = _op_scl_padoen_o[Ii];
            }
        else if(_op_scl_padoen_o[Ii] != _op_scl_padoen_o_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[14]->port[Ii]->output.pvalue))->state = _op_scl_padoen_o[Ii];
            mif_private->conn[14]->port[Ii]->delay = ((_op_scl_padoen_o[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[14]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[14]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[15]->size;Ii++)
    {
        if(temp_sda_pad_o[Ii]==0)
        {
            _op_sda_pad_o[Ii]=ZERO;
            }
        else if(temp_sda_pad_o[Ii]==1)
        {
            _op_sda_pad_o[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[15]->port[Ii]->output.pvalue))->state = _op_sda_pad_o[Ii];
            }
        else if(_op_sda_pad_o[Ii] != _op_sda_pad_o_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[15]->port[Ii]->output.pvalue))->state = _op_sda_pad_o[Ii];
            mif_private->conn[15]->port[Ii]->delay = ((_op_sda_pad_o[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[15]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[15]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[16]->size;Ii++)
    {
        if(temp_sda_padoen_o[Ii]==0)
        {
            _op_sda_padoen_o[Ii]=ZERO;
            }
        else if(temp_sda_padoen_o[Ii]==1)
        {
            _op_sda_padoen_o[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[16]->port[Ii]->output.pvalue))->state = _op_sda_padoen_o[Ii];
            }
        else if(_op_sda_padoen_o[Ii] != _op_sda_padoen_o_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[16]->port[Ii]->output.pvalue))->state = _op_sda_padoen_o[Ii];
            mif_private->conn[16]->port[Ii]->delay = ((_op_sda_padoen_o[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[16]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[16]->port[Ii]->output.pvalue))->strength = STRONG;
    }

}