#include "ngspice/cm.h"
extern void cm_calculator(Mif_Private_t *);
/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_calculator.h"

        
void cm_calculator(Mif_Private_t *mif_private) 
{
	Digital_State_t *_op_res, *_op_res_old;
	Digital_State_t *_op_seven_out, *_op_seven_out_old;

    static int inst_count=0;
    int count=0;
        
    if(mif_private->circuit.init)
    {   
        inst_count++;
        mif_private->param[0]->element[0].rvalue=inst_count;
        foocalculator(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_astr=mif_private->conn[0]->size;

        port_res=mif_private->conn[1]->size;

        port_seven_out=mif_private->conn[2]->size;
		cm_event_alloc(0,4*sizeof(Digital_State_t));
		cm_event_alloc(1,7*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
		{
			mif_private->conn[0]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}

		/*Retrieve Storage for output*/
		_op_res = _op_res_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_seven_out = _op_seven_out_old = (Digital_State_t *) cm_event_get_ptr(1,0);


	}
	else
	{
		_op_res = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_res_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_seven_out = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_seven_out_old = (Digital_State_t *) cm_event_get_ptr(1,2);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)mif_private->param[0]->element[0].rvalue;

    for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[0]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_astr[Ii]=0;            }
        else
        {
            temp_astr[Ii]=1;
        }
            }
	foocalculator(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
    {
        if(temp_res[Ii]==0)
        {
            _op_res[Ii]=ZERO;
            }
        else if(temp_res[Ii]==1)
        {
            _op_res[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[1]->port[Ii]->output.pvalue))->state = _op_res[Ii];
            }
        else if(_op_res[Ii] != _op_res_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[1]->port[Ii]->output.pvalue))->state = _op_res[Ii];
            mif_private->conn[1]->port[Ii]->delay = ((_op_res[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[1]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[1]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
    {
        if(temp_seven_out[Ii]==0)
        {
            _op_seven_out[Ii]=ZERO;
            }
        else if(temp_seven_out[Ii]==1)
        {
            _op_seven_out[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[2]->port[Ii]->output.pvalue))->state = _op_seven_out[Ii];
            }
        else if(_op_seven_out[Ii] != _op_seven_out_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[2]->port[Ii]->output.pvalue))->state = _op_seven_out[Ii];
            mif_private->conn[2]->port[Ii]->delay = ((_op_seven_out[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[2]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[2]->port[Ii]->output.pvalue))->strength = STRONG;
    }

}