int foo(int,int);
        int temp_d[1024];
        int port_d;
        int temp_rstn[1024];
        int port_rstn;
        int temp_clk[1024];
        int port_clk;
        int temp_q[1024];
        int port_q;