#include "ngspice/cm.h"
extern void cm_fir91(Mif_Private_t *);
/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_fir91.h"

        
void cm_fir91(Mif_Private_t *mif_private) 
{
	Digital_State_t *_op_ast_source_data, *_op_ast_source_data_old;
	Digital_State_t *_op_ast_sink_ready, *_op_ast_sink_ready_old;
	Digital_State_t *_op_ast_source_valid, *_op_ast_source_valid_old;
	Digital_State_t *_op_ast_source_error, *_op_ast_source_error_old;

    static int inst_count=0;
    int count=0;
        
    if(mif_private->circuit.init)
    {   
        inst_count++;
        mif_private->param[0]->element[0].rvalue=inst_count;
        foofir91(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk=mif_private->conn[0]->size;

        port_reset_n=mif_private->conn[1]->size;

        port_ast_sink_data=mif_private->conn[2]->size;

        port_coef_set=mif_private->conn[3]->size;

        port_ast_sink_valid=mif_private->conn[4]->size;

        port_ast_source_ready=mif_private->conn[5]->size;

        port_ast_sink_error=mif_private->conn[6]->size;

        port_coef_set_in=mif_private->conn[7]->size;

        port_coef_we=mif_private->conn[8]->size;

        port_coef_in=mif_private->conn[9]->size;

        port_ast_source_data=mif_private->conn[10]->size;

        port_ast_sink_ready=mif_private->conn[11]->size;

        port_ast_source_valid=mif_private->conn[12]->size;

        port_ast_source_error=mif_private->conn[13]->size;
		cm_event_alloc(0,38*sizeof(Digital_State_t));
		cm_event_alloc(1,1*sizeof(Digital_State_t));
		cm_event_alloc(2,1*sizeof(Digital_State_t));
		cm_event_alloc(3,2*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
		{
			mif_private->conn[0]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
		{
			mif_private->conn[1]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
		{
			mif_private->conn[2]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
		{
			mif_private->conn[3]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
		{
			mif_private->conn[4]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
		{
			mif_private->conn[5]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
		{
			mif_private->conn[6]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
		{
			mif_private->conn[7]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
		{
			mif_private->conn[8]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[9]->size;Ii++)
		{
			mif_private->conn[9]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}

		/*Retrieve Storage for output*/
		_op_ast_source_data = _op_ast_source_data_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_ast_sink_ready = _op_ast_sink_ready_old = (Digital_State_t *) cm_event_get_ptr(1,0);
		_op_ast_source_valid = _op_ast_source_valid_old = (Digital_State_t *) cm_event_get_ptr(2,0);
		_op_ast_source_error = _op_ast_source_error_old = (Digital_State_t *) cm_event_get_ptr(3,0);


	}
	else
	{
		_op_ast_source_data = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_ast_source_data_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_ast_sink_ready = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_ast_sink_ready_old = (Digital_State_t *) cm_event_get_ptr(1,2);
		_op_ast_source_valid = (Digital_State_t *) cm_event_get_ptr(2,2);
		_op_ast_source_valid_old = (Digital_State_t *) cm_event_get_ptr(2,3);
		_op_ast_source_error = (Digital_State_t *) cm_event_get_ptr(3,3);
		_op_ast_source_error_old = (Digital_State_t *) cm_event_get_ptr(3,4);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)mif_private->param[0]->element[0].rvalue;

    for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[0]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[1]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_reset_n[Ii]=0;            }
        else
        {
            temp_reset_n[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[2]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_ast_sink_data[Ii]=0;            }
        else
        {
            temp_ast_sink_data[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[3]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_coef_set[Ii]=0;            }
        else
        {
            temp_coef_set[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[4]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_ast_sink_valid[Ii]=0;            }
        else
        {
            temp_ast_sink_valid[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[5]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_ast_source_ready[Ii]=0;            }
        else
        {
            temp_ast_source_ready[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[6]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_ast_sink_error[Ii]=0;            }
        else
        {
            temp_ast_sink_error[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[7]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_coef_set_in[Ii]=0;            }
        else
        {
            temp_coef_set_in[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[8]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_coef_we[Ii]=0;            }
        else
        {
            temp_coef_we[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[9]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[9]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_coef_in[Ii]=0;            }
        else
        {
            temp_coef_in[Ii]=1;
        }
            }
	foofir91(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[10]->size;Ii++)
    {
        if(temp_ast_source_data[Ii]==0)
        {
            _op_ast_source_data[Ii]=ZERO;
            }
        else if(temp_ast_source_data[Ii]==1)
        {
            _op_ast_source_data[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->state = _op_ast_source_data[Ii];
            }
        else if(_op_ast_source_data[Ii] != _op_ast_source_data_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->state = _op_ast_source_data[Ii];
            mif_private->conn[10]->port[Ii]->delay = ((_op_ast_source_data[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[10]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[11]->size;Ii++)
    {
        if(temp_ast_sink_ready[Ii]==0)
        {
            _op_ast_sink_ready[Ii]=ZERO;
            }
        else if(temp_ast_sink_ready[Ii]==1)
        {
            _op_ast_sink_ready[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->state = _op_ast_sink_ready[Ii];
            }
        else if(_op_ast_sink_ready[Ii] != _op_ast_sink_ready_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->state = _op_ast_sink_ready[Ii];
            mif_private->conn[11]->port[Ii]->delay = ((_op_ast_sink_ready[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[11]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[12]->size;Ii++)
    {
        if(temp_ast_source_valid[Ii]==0)
        {
            _op_ast_source_valid[Ii]=ZERO;
            }
        else if(temp_ast_source_valid[Ii]==1)
        {
            _op_ast_source_valid[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->state = _op_ast_source_valid[Ii];
            }
        else if(_op_ast_source_valid[Ii] != _op_ast_source_valid_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->state = _op_ast_source_valid[Ii];
            mif_private->conn[12]->port[Ii]->delay = ((_op_ast_source_valid[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[12]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[13]->size;Ii++)
    {
        if(temp_ast_source_error[Ii]==0)
        {
            _op_ast_source_error[Ii]=ZERO;
            }
        else if(temp_ast_source_error[Ii]==1)
        {
            _op_ast_source_error[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[13]->port[Ii]->output.pvalue))->state = _op_ast_source_error[Ii];
            }
        else if(_op_ast_source_error[Ii] != _op_ast_source_error_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[13]->port[Ii]->output.pvalue))->state = _op_ast_source_error[Ii];
            mif_private->conn[13]->port[Ii]->delay = ((_op_ast_source_error[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[13]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[13]->port[Ii]->output.pvalue))->strength = STRONG;
    }

}