/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_division.h"

        
void cm_division(ARGS) 
{
	Digital_State_t *_op_exception, *_op_exception_old;
	Digital_State_t *_op_res, *_op_res_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {   
        inst_count++;
        PARAM(instance_id)=inst_count;
        foodivision(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_a=PORT_SIZE(a);

        port_b=PORT_SIZE(b);

        port_exception=PORT_SIZE(exception);

        port_res=PORT_SIZE(res);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		cm_event_alloc(1,32*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(a);Ii++)
		{
			LOAD(a[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(b);Ii++)
		{
			LOAD(b[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_exception = _op_exception_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_res = _op_res_old = (Digital_State_t *) cm_event_get_ptr(1,0);


	}
	else
	{
		_op_exception = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_exception_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_res = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_res_old = (Digital_State_t *) cm_event_get_ptr(1,2);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(a);Ii++)
    {
        if( INPUT_STATE(a[Ii])==ZERO )
        {
            temp_a[Ii]=0;            }
        else
        {
            temp_a[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(b);Ii++)
    {
        if( INPUT_STATE(b[Ii])==ZERO )
        {
            temp_b[Ii]=0;            }
        else
        {
            temp_b[Ii]=1;
        }
            }
	foodivision(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(exception);Ii++)
    {
        if(temp_exception[Ii]==0)
        {
            _op_exception[Ii]=ZERO;
            }
        else if(temp_exception[Ii]==1)
        {
            _op_exception[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(exception[Ii]) = _op_exception[Ii];
            }
        else if(_op_exception[Ii] != _op_exception_old[Ii])
        {
            OUTPUT_STATE(exception[Ii]) = _op_exception[Ii];
            OUTPUT_DELAY(exception[Ii]) = ((_op_exception[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(exception[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(exception[Ii]) = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(res);Ii++)
    {
        if(temp_res[Ii]==0)
        {
            _op_res[Ii]=ZERO;
            }
        else if(temp_res[Ii]==1)
        {
            _op_res[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(res[Ii]) = _op_res[Ii];
            }
        else if(_op_res[Ii] != _op_res_old[Ii])
        {
            OUTPUT_STATE(res[Ii]) = _op_res[Ii];
            OUTPUT_DELAY(res[Ii]) = ((_op_res[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(res[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(res[Ii]) = STRONG;
    }

}