int foojfsmmealywithoverlap(int,int);
        int temp_clock[1024];
        int port_clock;
        int temp_reset[1024];
        int port_reset;
        int temp_datain[1024];
        int port_datain;
        int temp_dataout[1024];
        int port_dataout;