#include "ngspice/cm.h"
extern void cm_cache(Mif_Private_t *);
/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_cache.h"

        
void cm_cache(Mif_Private_t *mif_private) 
{
	Digital_State_t *_op_out, *_op_out_old;
	Digital_State_t *_op_hit, *_op_hit_old;
	Digital_State_t *_op_miss, *_op_miss_old;

    static int inst_count=0;
    int count=0;
        
    if(mif_private->circuit.init)
    {   
        inst_count++;
        mif_private->param[0]->element[0].rvalue=inst_count;
        foocache(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_address=mif_private->conn[0]->size;

        port_set=mif_private->conn[1]->size;

        port_tag=mif_private->conn[2]->size;

        port_offset=mif_private->conn[3]->size;

        port_index=mif_private->conn[4]->size;

        port_selection_signal=mif_private->conn[5]->size;

        port_clk=mif_private->conn[6]->size;

        port_reset=mif_private->conn[7]->size;

        port_data_in=mif_private->conn[8]->size;

        port_write=mif_private->conn[9]->size;

        port_out=mif_private->conn[10]->size;

        port_hit=mif_private->conn[11]->size;

        port_miss=mif_private->conn[12]->size;
		cm_event_alloc(0,32*sizeof(Digital_State_t));
		cm_event_alloc(1,1*sizeof(Digital_State_t));
		cm_event_alloc(2,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
		{
			mif_private->conn[0]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
		{
			mif_private->conn[1]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
		{
			mif_private->conn[2]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
		{
			mif_private->conn[3]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
		{
			mif_private->conn[4]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
		{
			mif_private->conn[5]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
		{
			mif_private->conn[6]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
		{
			mif_private->conn[7]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
		{
			mif_private->conn[8]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[9]->size;Ii++)
		{
			mif_private->conn[9]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}

		/*Retrieve Storage for output*/
		_op_out = _op_out_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_hit = _op_hit_old = (Digital_State_t *) cm_event_get_ptr(1,0);
		_op_miss = _op_miss_old = (Digital_State_t *) cm_event_get_ptr(2,0);


	}
	else
	{
		_op_out = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_out_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_hit = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_hit_old = (Digital_State_t *) cm_event_get_ptr(1,2);
		_op_miss = (Digital_State_t *) cm_event_get_ptr(2,2);
		_op_miss_old = (Digital_State_t *) cm_event_get_ptr(2,3);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)mif_private->param[0]->element[0].rvalue;

    for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[0]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_address[Ii]=0;            }
        else
        {
            temp_address[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[1]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_set[Ii]=0;            }
        else
        {
            temp_set[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[2]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_tag[Ii]=0;            }
        else
        {
            temp_tag[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[3]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_offset[Ii]=0;            }
        else
        {
            temp_offset[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[4]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_index[Ii]=0;            }
        else
        {
            temp_index[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[5]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_selection_signal[Ii]=0;            }
        else
        {
            temp_selection_signal[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[6]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[7]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_reset[Ii]=0;            }
        else
        {
            temp_reset[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[8]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_data_in[Ii]=0;            }
        else
        {
            temp_data_in[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[9]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[9]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_write[Ii]=0;            }
        else
        {
            temp_write[Ii]=1;
        }
            }
	foocache(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[10]->size;Ii++)
    {
        if(temp_out[Ii]==0)
        {
            _op_out[Ii]=ZERO;
            }
        else if(temp_out[Ii]==1)
        {
            _op_out[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->state = _op_out[Ii];
            }
        else if(_op_out[Ii] != _op_out_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->state = _op_out[Ii];
            mif_private->conn[10]->port[Ii]->delay = ((_op_out[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[10]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[11]->size;Ii++)
    {
        if(temp_hit[Ii]==0)
        {
            _op_hit[Ii]=ZERO;
            }
        else if(temp_hit[Ii]==1)
        {
            _op_hit[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->state = _op_hit[Ii];
            }
        else if(_op_hit[Ii] != _op_hit_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->state = _op_hit[Ii];
            mif_private->conn[11]->port[Ii]->delay = ((_op_hit[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[11]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[12]->size;Ii++)
    {
        if(temp_miss[Ii]==0)
        {
            _op_miss[Ii]=ZERO;
            }
        else if(temp_miss[Ii]==1)
        {
            _op_miss[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->state = _op_miss[Ii];
            }
        else if(_op_miss[Ii] != _op_miss_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->state = _op_miss[Ii];
            mif_private->conn[12]->port[Ii]->delay = ((_op_miss[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[12]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->strength = STRONG;
    }

}