/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_cam.h"

        
void cm_cam(ARGS) 
{
	Digital_State_t *_op_cam_hit_out, *_op_cam_hit_out_old;
	Digital_State_t *_op_cam_addr_out, *_op_cam_addr_out_old;

    static int inst_count=0;
    int count=0;
        
    if(INIT)
    {   
        inst_count++;
        PARAM(instance_id)=inst_count;
        foocam(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk=PORT_SIZE(clk);

        port_cam_enable=PORT_SIZE(cam_enable);

        port_cam_data_in=PORT_SIZE(cam_data_in);

        port_cam_hit_out=PORT_SIZE(cam_hit_out);

        port_cam_addr_out=PORT_SIZE(cam_addr_out);
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		cm_event_alloc(1,8*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
		{
			LOAD(clk[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(cam_enable);Ii++)
		{
			LOAD(cam_enable[Ii])=PARAM(input_load); 
		}
		for(Ii=0;Ii<PORT_SIZE(cam_data_in);Ii++)
		{
			LOAD(cam_data_in[Ii])=PARAM(input_load); 
		}

		/*Retrieve Storage for output*/
		_op_cam_hit_out = _op_cam_hit_out_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_cam_addr_out = _op_cam_addr_out_old = (Digital_State_t *) cm_event_get_ptr(1,0);


	}
	else
	{
		_op_cam_hit_out = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_cam_hit_out_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_cam_addr_out = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_cam_addr_out_old = (Digital_State_t *) cm_event_get_ptr(1,2);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)PARAM(instance_id);

    for(Ii=0;Ii<PORT_SIZE(clk);Ii++)
    {
        if( INPUT_STATE(clk[Ii])==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(cam_enable);Ii++)
    {
        if( INPUT_STATE(cam_enable[Ii])==ZERO )
        {
            temp_cam_enable[Ii]=0;            }
        else
        {
            temp_cam_enable[Ii]=1;
        }
            }
    for(Ii=0;Ii<PORT_SIZE(cam_data_in);Ii++)
    {
        if( INPUT_STATE(cam_data_in[Ii])==ZERO )
        {
            temp_cam_data_in[Ii]=0;            }
        else
        {
            temp_cam_data_in[Ii]=1;
        }
            }
	foocam(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(cam_hit_out);Ii++)
    {
        if(temp_cam_hit_out[Ii]==0)
        {
            _op_cam_hit_out[Ii]=ZERO;
            }
        else if(temp_cam_hit_out[Ii]==1)
        {
            _op_cam_hit_out[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(cam_hit_out[Ii]) = _op_cam_hit_out[Ii];
            }
        else if(_op_cam_hit_out[Ii] != _op_cam_hit_out_old[Ii])
        {
            OUTPUT_STATE(cam_hit_out[Ii]) = _op_cam_hit_out[Ii];
            OUTPUT_DELAY(cam_hit_out[Ii]) = ((_op_cam_hit_out[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(cam_hit_out[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(cam_hit_out[Ii]) = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<PORT_SIZE(cam_addr_out);Ii++)
    {
        if(temp_cam_addr_out[Ii]==0)
        {
            _op_cam_addr_out[Ii]=ZERO;
            }
        else if(temp_cam_addr_out[Ii]==1)
        {
            _op_cam_addr_out[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(ANALYSIS == DC)
        {
            OUTPUT_STATE(cam_addr_out[Ii]) = _op_cam_addr_out[Ii];
            }
        else if(_op_cam_addr_out[Ii] != _op_cam_addr_out_old[Ii])
        {
            OUTPUT_STATE(cam_addr_out[Ii]) = _op_cam_addr_out[Ii];
            OUTPUT_DELAY(cam_addr_out[Ii]) = ((_op_cam_addr_out[Ii] == ZERO) ? PARAM(fall_delay) : PARAM(rise_delay));
            }
        else
        {
            OUTPUT_CHANGED(cam_addr_out[Ii]) = FALSE;
            }
        OUTPUT_STRENGTH(cam_addr_out[Ii]) = STRONG;
    }

}