#include "ngspice/cm.h"
extern void cm_spi(Mif_Private_t *);
/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_spi.h"

        
void cm_spi(Mif_Private_t *mif_private) 
{
	Digital_State_t *_op_out_data, *_op_out_data_old;

    static int inst_count=0;
    int count=0;
        
    if(mif_private->circuit.init)
    {   
        inst_count++;
        mif_private->param[0]->element[0].rvalue=inst_count;
        foospi(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_in_data=mif_private->conn[0]->size;

        port_clk=mif_private->conn[1]->size;

        port_addr=mif_private->conn[2]->size;

        port_wr=mif_private->conn[3]->size;

        port_rd=mif_private->conn[4]->size;

        port_cs=mif_private->conn[5]->size;

        port_mosi=mif_private->conn[6]->size;

        port_miso=mif_private->conn[7]->size;

        port_sclk=mif_private->conn[8]->size;

        port_out_data=mif_private->conn[9]->size;
		cm_event_alloc(0,8*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
		{
			mif_private->conn[0]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
		{
			mif_private->conn[1]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
		{
			mif_private->conn[2]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
		{
			mif_private->conn[3]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
		{
			mif_private->conn[4]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
		{
			mif_private->conn[5]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
		{
			mif_private->conn[6]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
		{
			mif_private->conn[7]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
		{
			mif_private->conn[8]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}

		/*Retrieve Storage for output*/
		_op_out_data = _op_out_data_old = (Digital_State_t *) cm_event_get_ptr(0,0);


	}
	else
	{
		_op_out_data = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_out_data_old = (Digital_State_t *) cm_event_get_ptr(0,1);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)mif_private->param[0]->element[0].rvalue;

    for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[0]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_in_data[Ii]=0;            }
        else
        {
            temp_in_data[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[1]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[2]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_addr[Ii]=0;            }
        else
        {
            temp_addr[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[3]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_wr[Ii]=0;            }
        else
        {
            temp_wr[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[4]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_rd[Ii]=0;            }
        else
        {
            temp_rd[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[5]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_cs[Ii]=0;            }
        else
        {
            temp_cs[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[6]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_mosi[Ii]=0;            }
        else
        {
            temp_mosi[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[7]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_miso[Ii]=0;            }
        else
        {
            temp_miso[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[8]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_sclk[Ii]=0;            }
        else
        {
            temp_sclk[Ii]=1;
        }
            }
	foospi(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[9]->size;Ii++)
    {
        if(temp_out_data[Ii]==0)
        {
            _op_out_data[Ii]=ZERO;
            }
        else if(temp_out_data[Ii]==1)
        {
            _op_out_data[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[9]->port[Ii]->output.pvalue))->state = _op_out_data[Ii];
            }
        else if(_op_out_data[Ii] != _op_out_data_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[9]->port[Ii]->output.pvalue))->state = _op_out_data[Ii];
            mif_private->conn[9]->port[Ii]->delay = ((_op_out_data[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[9]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[9]->port[Ii]->output.pvalue))->strength = STRONG;
    }

}