#include "ngspice/cm.h"
extern void cm_ddr2_controller(Mif_Private_t *);
/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_ddr2_controller.h"

        
void cm_ddr2_controller(Mif_Private_t *mif_private) 
{
	Digital_State_t *_op_DOUT, *_op_DOUT_old;
	Digital_State_t *_op_RADDR, *_op_RADDR_old;
	Digital_State_t *_op_FILLCOUNT, *_op_FILLCOUNT_old;
	Digital_State_t *_op_VALIDOUT, *_op_VALIDOUT_old;
	Digital_State_t *_op_NOTFULL, *_op_NOTFULL_old;
	Digital_State_t *_op_READY, *_op_READY_old;
	Digital_State_t *_op_C0_DM_PAD, *_op_C0_DM_PAD_old;
	Digital_State_t *_op_C0_ODT_PAD, *_op_C0_ODT_PAD_old;
	Digital_State_t *_op_C0_CK_PAD, *_op_C0_CK_PAD_old;
	Digital_State_t *_op_C0_CKBAR_PAD, *_op_C0_CKBAR_PAD_old;
	Digital_State_t *_op_C0_CKE_PAD, *_op_C0_CKE_PAD_old;
	Digital_State_t *_op_C0_CSBAR_PAD, *_op_C0_CSBAR_PAD_old;
	Digital_State_t *_op_C0_RASBAR_PAD, *_op_C0_RASBAR_PAD_old;
	Digital_State_t *_op_C0_CASBAR_PAD, *_op_C0_CASBAR_PAD_old;
	Digital_State_t *_op_C0_WEBAR_PAD, *_op_C0_WEBAR_PAD_old;
	Digital_State_t *_op_C0_BA_PAD, *_op_C0_BA_PAD_old;
	Digital_State_t *_op_C0_A_PAD, *_op_C0_A_PAD_old;

    static int inst_count=0;
    int count=0;
        
    if(mif_private->circuit.init)
    {   
        inst_count++;
        mif_private->param[0]->element[0].rvalue=inst_count;
        fooddr2_controller(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_CLK=mif_private->conn[0]->size;

        port_RESET=mif_private->conn[1]->size;

        port_CMD=mif_private->conn[2]->size;

        port_SZ=mif_private->conn[3]->size;

        port_OP=mif_private->conn[4]->size;

        port_FETCHING=mif_private->conn[5]->size;

        port_DIN=mif_private->conn[6]->size;

        port_ADDR=mif_private->conn[7]->size;

        port_INITDDR=mif_private->conn[8]->size;

        port_DOUT=mif_private->conn[9]->size;

        port_RADDR=mif_private->conn[10]->size;

        port_FILLCOUNT=mif_private->conn[11]->size;

        port_VALIDOUT=mif_private->conn[12]->size;

        port_NOTFULL=mif_private->conn[13]->size;

        port_READY=mif_private->conn[14]->size;

        port_C0_DM_PAD=mif_private->conn[15]->size;

        port_C0_ODT_PAD=mif_private->conn[16]->size;

        port_C0_CK_PAD=mif_private->conn[17]->size;

        port_C0_CKBAR_PAD=mif_private->conn[18]->size;

        port_C0_CKE_PAD=mif_private->conn[19]->size;

        port_C0_CSBAR_PAD=mif_private->conn[20]->size;

        port_C0_RASBAR_PAD=mif_private->conn[21]->size;

        port_C0_CASBAR_PAD=mif_private->conn[22]->size;

        port_C0_WEBAR_PAD=mif_private->conn[23]->size;

        port_C0_BA_PAD=mif_private->conn[24]->size;

        port_C0_A_PAD=mif_private->conn[25]->size;
		cm_event_alloc(0,16*sizeof(Digital_State_t));
		cm_event_alloc(1,25*sizeof(Digital_State_t));
		cm_event_alloc(2,7*sizeof(Digital_State_t));
		cm_event_alloc(3,1*sizeof(Digital_State_t));
		cm_event_alloc(4,1*sizeof(Digital_State_t));
		cm_event_alloc(5,1*sizeof(Digital_State_t));
		cm_event_alloc(6,2*sizeof(Digital_State_t));
		cm_event_alloc(7,1*sizeof(Digital_State_t));
		cm_event_alloc(8,1*sizeof(Digital_State_t));
		cm_event_alloc(9,1*sizeof(Digital_State_t));
		cm_event_alloc(10,1*sizeof(Digital_State_t));
		cm_event_alloc(11,1*sizeof(Digital_State_t));
		cm_event_alloc(12,1*sizeof(Digital_State_t));
		cm_event_alloc(13,1*sizeof(Digital_State_t));
		cm_event_alloc(14,1*sizeof(Digital_State_t));
		cm_event_alloc(15,2*sizeof(Digital_State_t));
		cm_event_alloc(16,13*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
		{
			mif_private->conn[0]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
		{
			mif_private->conn[1]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
		{
			mif_private->conn[2]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
		{
			mif_private->conn[3]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
		{
			mif_private->conn[4]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
		{
			mif_private->conn[5]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
		{
			mif_private->conn[6]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
		{
			mif_private->conn[7]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
		{
			mif_private->conn[8]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}

		/*Retrieve Storage for output*/
		_op_DOUT = _op_DOUT_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_RADDR = _op_RADDR_old = (Digital_State_t *) cm_event_get_ptr(1,0);
		_op_FILLCOUNT = _op_FILLCOUNT_old = (Digital_State_t *) cm_event_get_ptr(2,0);
		_op_VALIDOUT = _op_VALIDOUT_old = (Digital_State_t *) cm_event_get_ptr(3,0);
		_op_NOTFULL = _op_NOTFULL_old = (Digital_State_t *) cm_event_get_ptr(4,0);
		_op_READY = _op_READY_old = (Digital_State_t *) cm_event_get_ptr(5,0);
		_op_C0_DM_PAD = _op_C0_DM_PAD_old = (Digital_State_t *) cm_event_get_ptr(6,0);
		_op_C0_ODT_PAD = _op_C0_ODT_PAD_old = (Digital_State_t *) cm_event_get_ptr(7,0);
		_op_C0_CK_PAD = _op_C0_CK_PAD_old = (Digital_State_t *) cm_event_get_ptr(8,0);
		_op_C0_CKBAR_PAD = _op_C0_CKBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(9,0);
		_op_C0_CKE_PAD = _op_C0_CKE_PAD_old = (Digital_State_t *) cm_event_get_ptr(10,0);
		_op_C0_CSBAR_PAD = _op_C0_CSBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(11,0);
		_op_C0_RASBAR_PAD = _op_C0_RASBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(12,0);
		_op_C0_CASBAR_PAD = _op_C0_CASBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(13,0);
		_op_C0_WEBAR_PAD = _op_C0_WEBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(14,0);
		_op_C0_BA_PAD = _op_C0_BA_PAD_old = (Digital_State_t *) cm_event_get_ptr(15,0);
		_op_C0_A_PAD = _op_C0_A_PAD_old = (Digital_State_t *) cm_event_get_ptr(16,0);


	}
	else
	{
		_op_DOUT = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_DOUT_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_RADDR = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_RADDR_old = (Digital_State_t *) cm_event_get_ptr(1,2);
		_op_FILLCOUNT = (Digital_State_t *) cm_event_get_ptr(2,2);
		_op_FILLCOUNT_old = (Digital_State_t *) cm_event_get_ptr(2,3);
		_op_VALIDOUT = (Digital_State_t *) cm_event_get_ptr(3,3);
		_op_VALIDOUT_old = (Digital_State_t *) cm_event_get_ptr(3,4);
		_op_NOTFULL = (Digital_State_t *) cm_event_get_ptr(4,4);
		_op_NOTFULL_old = (Digital_State_t *) cm_event_get_ptr(4,5);
		_op_READY = (Digital_State_t *) cm_event_get_ptr(5,5);
		_op_READY_old = (Digital_State_t *) cm_event_get_ptr(5,6);
		_op_C0_DM_PAD = (Digital_State_t *) cm_event_get_ptr(6,6);
		_op_C0_DM_PAD_old = (Digital_State_t *) cm_event_get_ptr(6,7);
		_op_C0_ODT_PAD = (Digital_State_t *) cm_event_get_ptr(7,7);
		_op_C0_ODT_PAD_old = (Digital_State_t *) cm_event_get_ptr(7,8);
		_op_C0_CK_PAD = (Digital_State_t *) cm_event_get_ptr(8,8);
		_op_C0_CK_PAD_old = (Digital_State_t *) cm_event_get_ptr(8,9);
		_op_C0_CKBAR_PAD = (Digital_State_t *) cm_event_get_ptr(9,9);
		_op_C0_CKBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(9,10);
		_op_C0_CKE_PAD = (Digital_State_t *) cm_event_get_ptr(10,10);
		_op_C0_CKE_PAD_old = (Digital_State_t *) cm_event_get_ptr(10,11);
		_op_C0_CSBAR_PAD = (Digital_State_t *) cm_event_get_ptr(11,11);
		_op_C0_CSBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(11,12);
		_op_C0_RASBAR_PAD = (Digital_State_t *) cm_event_get_ptr(12,12);
		_op_C0_RASBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(12,13);
		_op_C0_CASBAR_PAD = (Digital_State_t *) cm_event_get_ptr(13,13);
		_op_C0_CASBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(13,14);
		_op_C0_WEBAR_PAD = (Digital_State_t *) cm_event_get_ptr(14,14);
		_op_C0_WEBAR_PAD_old = (Digital_State_t *) cm_event_get_ptr(14,15);
		_op_C0_BA_PAD = (Digital_State_t *) cm_event_get_ptr(15,15);
		_op_C0_BA_PAD_old = (Digital_State_t *) cm_event_get_ptr(15,16);
		_op_C0_A_PAD = (Digital_State_t *) cm_event_get_ptr(16,16);
		_op_C0_A_PAD_old = (Digital_State_t *) cm_event_get_ptr(16,17);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)mif_private->param[0]->element[0].rvalue;

    for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[0]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_CLK[Ii]=0;            }
        else
        {
            temp_CLK[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[1]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_RESET[Ii]=0;            }
        else
        {
            temp_RESET[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[2]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_CMD[Ii]=0;            }
        else
        {
            temp_CMD[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[3]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_SZ[Ii]=0;            }
        else
        {
            temp_SZ[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[4]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_OP[Ii]=0;            }
        else
        {
            temp_OP[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[5]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_FETCHING[Ii]=0;            }
        else
        {
            temp_FETCHING[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[6]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_DIN[Ii]=0;            }
        else
        {
            temp_DIN[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[7]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_ADDR[Ii]=0;            }
        else
        {
            temp_ADDR[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[8]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_INITDDR[Ii]=0;            }
        else
        {
            temp_INITDDR[Ii]=1;
        }
            }
	fooddr2_controller(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[9]->size;Ii++)
    {
        if(temp_DOUT[Ii]==0)
        {
            _op_DOUT[Ii]=ZERO;
            }
        else if(temp_DOUT[Ii]==1)
        {
            _op_DOUT[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[9]->port[Ii]->output.pvalue))->state = _op_DOUT[Ii];
            }
        else if(_op_DOUT[Ii] != _op_DOUT_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[9]->port[Ii]->output.pvalue))->state = _op_DOUT[Ii];
            mif_private->conn[9]->port[Ii]->delay = ((_op_DOUT[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[9]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[9]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[10]->size;Ii++)
    {
        if(temp_RADDR[Ii]==0)
        {
            _op_RADDR[Ii]=ZERO;
            }
        else if(temp_RADDR[Ii]==1)
        {
            _op_RADDR[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->state = _op_RADDR[Ii];
            }
        else if(_op_RADDR[Ii] != _op_RADDR_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->state = _op_RADDR[Ii];
            mif_private->conn[10]->port[Ii]->delay = ((_op_RADDR[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[10]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[10]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[11]->size;Ii++)
    {
        if(temp_FILLCOUNT[Ii]==0)
        {
            _op_FILLCOUNT[Ii]=ZERO;
            }
        else if(temp_FILLCOUNT[Ii]==1)
        {
            _op_FILLCOUNT[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->state = _op_FILLCOUNT[Ii];
            }
        else if(_op_FILLCOUNT[Ii] != _op_FILLCOUNT_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->state = _op_FILLCOUNT[Ii];
            mif_private->conn[11]->port[Ii]->delay = ((_op_FILLCOUNT[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[11]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[11]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[12]->size;Ii++)
    {
        if(temp_VALIDOUT[Ii]==0)
        {
            _op_VALIDOUT[Ii]=ZERO;
            }
        else if(temp_VALIDOUT[Ii]==1)
        {
            _op_VALIDOUT[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->state = _op_VALIDOUT[Ii];
            }
        else if(_op_VALIDOUT[Ii] != _op_VALIDOUT_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->state = _op_VALIDOUT[Ii];
            mif_private->conn[12]->port[Ii]->delay = ((_op_VALIDOUT[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[12]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[12]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[13]->size;Ii++)
    {
        if(temp_NOTFULL[Ii]==0)
        {
            _op_NOTFULL[Ii]=ZERO;
            }
        else if(temp_NOTFULL[Ii]==1)
        {
            _op_NOTFULL[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[13]->port[Ii]->output.pvalue))->state = _op_NOTFULL[Ii];
            }
        else if(_op_NOTFULL[Ii] != _op_NOTFULL_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[13]->port[Ii]->output.pvalue))->state = _op_NOTFULL[Ii];
            mif_private->conn[13]->port[Ii]->delay = ((_op_NOTFULL[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[13]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[13]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[14]->size;Ii++)
    {
        if(temp_READY[Ii]==0)
        {
            _op_READY[Ii]=ZERO;
            }
        else if(temp_READY[Ii]==1)
        {
            _op_READY[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[14]->port[Ii]->output.pvalue))->state = _op_READY[Ii];
            }
        else if(_op_READY[Ii] != _op_READY_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[14]->port[Ii]->output.pvalue))->state = _op_READY[Ii];
            mif_private->conn[14]->port[Ii]->delay = ((_op_READY[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[14]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[14]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[15]->size;Ii++)
    {
        if(temp_C0_DM_PAD[Ii]==0)
        {
            _op_C0_DM_PAD[Ii]=ZERO;
            }
        else if(temp_C0_DM_PAD[Ii]==1)
        {
            _op_C0_DM_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[15]->port[Ii]->output.pvalue))->state = _op_C0_DM_PAD[Ii];
            }
        else if(_op_C0_DM_PAD[Ii] != _op_C0_DM_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[15]->port[Ii]->output.pvalue))->state = _op_C0_DM_PAD[Ii];
            mif_private->conn[15]->port[Ii]->delay = ((_op_C0_DM_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[15]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[15]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[16]->size;Ii++)
    {
        if(temp_C0_ODT_PAD[Ii]==0)
        {
            _op_C0_ODT_PAD[Ii]=ZERO;
            }
        else if(temp_C0_ODT_PAD[Ii]==1)
        {
            _op_C0_ODT_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[16]->port[Ii]->output.pvalue))->state = _op_C0_ODT_PAD[Ii];
            }
        else if(_op_C0_ODT_PAD[Ii] != _op_C0_ODT_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[16]->port[Ii]->output.pvalue))->state = _op_C0_ODT_PAD[Ii];
            mif_private->conn[16]->port[Ii]->delay = ((_op_C0_ODT_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[16]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[16]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[17]->size;Ii++)
    {
        if(temp_C0_CK_PAD[Ii]==0)
        {
            _op_C0_CK_PAD[Ii]=ZERO;
            }
        else if(temp_C0_CK_PAD[Ii]==1)
        {
            _op_C0_CK_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[17]->port[Ii]->output.pvalue))->state = _op_C0_CK_PAD[Ii];
            }
        else if(_op_C0_CK_PAD[Ii] != _op_C0_CK_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[17]->port[Ii]->output.pvalue))->state = _op_C0_CK_PAD[Ii];
            mif_private->conn[17]->port[Ii]->delay = ((_op_C0_CK_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[17]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[17]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[18]->size;Ii++)
    {
        if(temp_C0_CKBAR_PAD[Ii]==0)
        {
            _op_C0_CKBAR_PAD[Ii]=ZERO;
            }
        else if(temp_C0_CKBAR_PAD[Ii]==1)
        {
            _op_C0_CKBAR_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[18]->port[Ii]->output.pvalue))->state = _op_C0_CKBAR_PAD[Ii];
            }
        else if(_op_C0_CKBAR_PAD[Ii] != _op_C0_CKBAR_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[18]->port[Ii]->output.pvalue))->state = _op_C0_CKBAR_PAD[Ii];
            mif_private->conn[18]->port[Ii]->delay = ((_op_C0_CKBAR_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[18]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[18]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[19]->size;Ii++)
    {
        if(temp_C0_CKE_PAD[Ii]==0)
        {
            _op_C0_CKE_PAD[Ii]=ZERO;
            }
        else if(temp_C0_CKE_PAD[Ii]==1)
        {
            _op_C0_CKE_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[19]->port[Ii]->output.pvalue))->state = _op_C0_CKE_PAD[Ii];
            }
        else if(_op_C0_CKE_PAD[Ii] != _op_C0_CKE_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[19]->port[Ii]->output.pvalue))->state = _op_C0_CKE_PAD[Ii];
            mif_private->conn[19]->port[Ii]->delay = ((_op_C0_CKE_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[19]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[19]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[20]->size;Ii++)
    {
        if(temp_C0_CSBAR_PAD[Ii]==0)
        {
            _op_C0_CSBAR_PAD[Ii]=ZERO;
            }
        else if(temp_C0_CSBAR_PAD[Ii]==1)
        {
            _op_C0_CSBAR_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[20]->port[Ii]->output.pvalue))->state = _op_C0_CSBAR_PAD[Ii];
            }
        else if(_op_C0_CSBAR_PAD[Ii] != _op_C0_CSBAR_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[20]->port[Ii]->output.pvalue))->state = _op_C0_CSBAR_PAD[Ii];
            mif_private->conn[20]->port[Ii]->delay = ((_op_C0_CSBAR_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[20]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[20]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[21]->size;Ii++)
    {
        if(temp_C0_RASBAR_PAD[Ii]==0)
        {
            _op_C0_RASBAR_PAD[Ii]=ZERO;
            }
        else if(temp_C0_RASBAR_PAD[Ii]==1)
        {
            _op_C0_RASBAR_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[21]->port[Ii]->output.pvalue))->state = _op_C0_RASBAR_PAD[Ii];
            }
        else if(_op_C0_RASBAR_PAD[Ii] != _op_C0_RASBAR_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[21]->port[Ii]->output.pvalue))->state = _op_C0_RASBAR_PAD[Ii];
            mif_private->conn[21]->port[Ii]->delay = ((_op_C0_RASBAR_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[21]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[21]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[22]->size;Ii++)
    {
        if(temp_C0_CASBAR_PAD[Ii]==0)
        {
            _op_C0_CASBAR_PAD[Ii]=ZERO;
            }
        else if(temp_C0_CASBAR_PAD[Ii]==1)
        {
            _op_C0_CASBAR_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[22]->port[Ii]->output.pvalue))->state = _op_C0_CASBAR_PAD[Ii];
            }
        else if(_op_C0_CASBAR_PAD[Ii] != _op_C0_CASBAR_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[22]->port[Ii]->output.pvalue))->state = _op_C0_CASBAR_PAD[Ii];
            mif_private->conn[22]->port[Ii]->delay = ((_op_C0_CASBAR_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[22]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[22]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[23]->size;Ii++)
    {
        if(temp_C0_WEBAR_PAD[Ii]==0)
        {
            _op_C0_WEBAR_PAD[Ii]=ZERO;
            }
        else if(temp_C0_WEBAR_PAD[Ii]==1)
        {
            _op_C0_WEBAR_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[23]->port[Ii]->output.pvalue))->state = _op_C0_WEBAR_PAD[Ii];
            }
        else if(_op_C0_WEBAR_PAD[Ii] != _op_C0_WEBAR_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[23]->port[Ii]->output.pvalue))->state = _op_C0_WEBAR_PAD[Ii];
            mif_private->conn[23]->port[Ii]->delay = ((_op_C0_WEBAR_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[23]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[23]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[24]->size;Ii++)
    {
        if(temp_C0_BA_PAD[Ii]==0)
        {
            _op_C0_BA_PAD[Ii]=ZERO;
            }
        else if(temp_C0_BA_PAD[Ii]==1)
        {
            _op_C0_BA_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[24]->port[Ii]->output.pvalue))->state = _op_C0_BA_PAD[Ii];
            }
        else if(_op_C0_BA_PAD[Ii] != _op_C0_BA_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[24]->port[Ii]->output.pvalue))->state = _op_C0_BA_PAD[Ii];
            mif_private->conn[24]->port[Ii]->delay = ((_op_C0_BA_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[24]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[24]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[25]->size;Ii++)
    {
        if(temp_C0_A_PAD[Ii]==0)
        {
            _op_C0_A_PAD[Ii]=ZERO;
            }
        else if(temp_C0_A_PAD[Ii]==1)
        {
            _op_C0_A_PAD[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[25]->port[Ii]->output.pvalue))->state = _op_C0_A_PAD[Ii];
            }
        else if(_op_C0_A_PAD[Ii] != _op_C0_A_PAD_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[25]->port[Ii]->output.pvalue))->state = _op_C0_A_PAD[Ii];
            mif_private->conn[25]->port[Ii]->delay = ((_op_C0_A_PAD[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[25]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[25]->port[Ii]->output.pvalue))->strength = STRONG;
    }

}