
/*
 * Structures for model: ddr2_controller
 *
 * Automatically generated by cmpp preprocessor
 *
 * !!! DO NOT EDIT !!!
 *
 */


#include "ngspice/ngspice.h"
#include <stdio.h>
#include "ngspice/devdefs.h"
#include "ngspice/ifsim.h"
#include "ngspice/mifdefs.h"
#include "ngspice/mifproto.h"
#include "ngspice/mifparse.h"


static IFparm MIFmPTable[] = {
    IOP("instance_id", 0, IF_REAL, "instance_id"),
    IOP("input_load", 1, IF_REAL, "input load value (F)"),
    IOP("rise_delay", 2, IF_REAL, "rise delay"),
    IOP("fall_delay", 3, IF_REAL, "fall delay"),
};


static Mif_Port_Type_t MIFportEnum0[] = {
    MIF_DIGITAL,
};


static char *MIFportStr0[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum1[] = {
    MIF_DIGITAL,
};


static char *MIFportStr1[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum2[] = {
    MIF_DIGITAL,
};


static char *MIFportStr2[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum3[] = {
    MIF_DIGITAL,
};


static char *MIFportStr3[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum4[] = {
    MIF_DIGITAL,
};


static char *MIFportStr4[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum5[] = {
    MIF_DIGITAL,
};


static char *MIFportStr5[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum6[] = {
    MIF_DIGITAL,
};


static char *MIFportStr6[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum7[] = {
    MIF_DIGITAL,
};


static char *MIFportStr7[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum8[] = {
    MIF_DIGITAL,
};


static char *MIFportStr8[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum9[] = {
    MIF_DIGITAL,
};


static char *MIFportStr9[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum10[] = {
    MIF_DIGITAL,
};


static char *MIFportStr10[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum11[] = {
    MIF_DIGITAL,
};


static char *MIFportStr11[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum12[] = {
    MIF_DIGITAL,
};


static char *MIFportStr12[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum13[] = {
    MIF_DIGITAL,
};


static char *MIFportStr13[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum14[] = {
    MIF_DIGITAL,
};


static char *MIFportStr14[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum15[] = {
    MIF_DIGITAL,
};


static char *MIFportStr15[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum16[] = {
    MIF_DIGITAL,
};


static char *MIFportStr16[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum17[] = {
    MIF_DIGITAL,
};


static char *MIFportStr17[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum18[] = {
    MIF_DIGITAL,
};


static char *MIFportStr18[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum19[] = {
    MIF_DIGITAL,
};


static char *MIFportStr19[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum20[] = {
    MIF_DIGITAL,
};


static char *MIFportStr20[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum21[] = {
    MIF_DIGITAL,
};


static char *MIFportStr21[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum22[] = {
    MIF_DIGITAL,
};


static char *MIFportStr22[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum23[] = {
    MIF_DIGITAL,
};


static char *MIFportStr23[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum24[] = {
    MIF_DIGITAL,
};


static char *MIFportStr24[] = {
    "d",
};


static Mif_Port_Type_t MIFportEnum25[] = {
    MIF_DIGITAL,
};


static char *MIFportStr25[] = {
    "d",
};


static Mif_Conn_Info_t MIFconnTable[] = {
  {
    "CLK",
    "input port CLK",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum0,
    MIFportStr0,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "RESET",
    "input port RESET",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum1,
    MIFportStr1,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "CMD",
    "input port CMD",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum2,
    MIFportStr2,
    MIF_TRUE,
    MIF_TRUE,
    3,
    MIF_TRUE,
    3,
    MIF_FALSE,
  },
  {
    "SZ",
    "input port SZ",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum3,
    MIFportStr3,
    MIF_TRUE,
    MIF_TRUE,
    2,
    MIF_TRUE,
    2,
    MIF_FALSE,
  },
  {
    "OP",
    "input port OP",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum4,
    MIFportStr4,
    MIF_TRUE,
    MIF_TRUE,
    3,
    MIF_TRUE,
    3,
    MIF_FALSE,
  },
  {
    "FETCHING",
    "input port FETCHING",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum5,
    MIFportStr5,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "DIN",
    "input port DIN",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum6,
    MIFportStr6,
    MIF_TRUE,
    MIF_TRUE,
    16,
    MIF_TRUE,
    16,
    MIF_FALSE,
  },
  {
    "ADDR",
    "input port ADDR",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum7,
    MIFportStr7,
    MIF_TRUE,
    MIF_TRUE,
    25,
    MIF_TRUE,
    25,
    MIF_FALSE,
  },
  {
    "INITDDR",
    "input port INITDDR",
    MIF_IN,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum8,
    MIFportStr8,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "DOUT",
    "output port DOUT",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum9,
    MIFportStr9,
    MIF_TRUE,
    MIF_TRUE,
    16,
    MIF_TRUE,
    16,
    MIF_FALSE,
  },
  {
    "RADDR",
    "output port RADDR",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum10,
    MIFportStr10,
    MIF_TRUE,
    MIF_TRUE,
    25,
    MIF_TRUE,
    25,
    MIF_FALSE,
  },
  {
    "FILLCOUNT",
    "output port FILLCOUNT",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum11,
    MIFportStr11,
    MIF_TRUE,
    MIF_TRUE,
    7,
    MIF_TRUE,
    7,
    MIF_FALSE,
  },
  {
    "VALIDOUT",
    "output port VALIDOUT",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum12,
    MIFportStr12,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "NOTFULL",
    "output port NOTFULL",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum13,
    MIFportStr13,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "READY",
    "output port READY",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum14,
    MIFportStr14,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "C0_DM_PAD",
    "output port C0_DM_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum15,
    MIFportStr15,
    MIF_TRUE,
    MIF_TRUE,
    2,
    MIF_TRUE,
    2,
    MIF_FALSE,
  },
  {
    "C0_ODT_PAD",
    "output port C0_ODT_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum16,
    MIFportStr16,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "C0_CK_PAD",
    "output port C0_CK_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum17,
    MIFportStr17,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "C0_CKBAR_PAD",
    "output port C0_CKBAR_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum18,
    MIFportStr18,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "C0_CKE_PAD",
    "output port C0_CKE_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum19,
    MIFportStr19,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "C0_CSBAR_PAD",
    "output port C0_CSBAR_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum20,
    MIFportStr20,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "C0_RASBAR_PAD",
    "output port C0_RASBAR_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum21,
    MIFportStr21,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "C0_CASBAR_PAD",
    "output port C0_CASBAR_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum22,
    MIFportStr22,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "C0_WEBAR_PAD",
    "output port C0_WEBAR_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum23,
    MIFportStr23,
    MIF_TRUE,
    MIF_TRUE,
    1,
    MIF_TRUE,
    1,
    MIF_FALSE,
  },
  {
    "C0_BA_PAD",
    "output port C0_BA_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum24,
    MIFportStr24,
    MIF_TRUE,
    MIF_TRUE,
    2,
    MIF_TRUE,
    2,
    MIF_FALSE,
  },
  {
    "C0_A_PAD",
    "output port C0_A_PAD",
    MIF_OUT,
    MIF_DIGITAL,
    "d",
    1,
    MIFportEnum25,
    MIFportStr25,
    MIF_TRUE,
    MIF_TRUE,
    13,
    MIF_TRUE,
    13,
    MIF_FALSE,
  },
};


static Mif_Param_Info_t MIFparamTable[] = {
  {
    "instance_id",
    "instance_id",
    MIF_REAL,
    MIF_TRUE,
    {MIF_FALSE, 0, 0.000000e+00, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "input_load",
    "input load value (F)",
    MIF_REAL,
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-12, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "rise_delay",
    "rise delay",
    MIF_REAL,
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-09, {0.0, 0.0}, NULL},
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-12, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
  {
    "fall_delay",
    "fall delay",
    MIF_REAL,
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-09, {0.0, 0.0}, NULL},
    MIF_TRUE,
    {MIF_FALSE, 0, 1.000000e-12, {0.0, 0.0}, NULL},
    MIF_FALSE,
    {MIF_FALSE, 0, 0.0, {0.0, 0.0}, NULL},
    MIF_FALSE,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_FALSE,
    0,
    MIF_TRUE,
  },
};


extern void cm_ddr2_controller(Mif_Private_t *);

static int val_terms             = 0;
static int val_numNames          = 0;
static int val_numInstanceParms  = 0;
static int val_numModelParms     = 4;
static int val_sizeofMIFinstance = sizeof(MIFinstance);
static int val_sizeofMIFmodel    = sizeof(MIFmodel);

SPICEdev cm_ddr2_controller_info = {
    .DEVpublic = {
        .name = "ddr2_controller",
        .description = "Model generated from ghdl code ddr2_controller.v",
        .terms = &val_terms,
        .numNames = &val_numNames,
        .termNames = NULL,
        .numInstanceParms = &val_numInstanceParms,
        .instanceParms = NULL,
        .numModelParms = &val_numModelParms,
        .modelParms = MIFmPTable,
        .flags = 0,

        .cm_func = cm_ddr2_controller,
        .num_conn = 26,
        .conn = MIFconnTable,
        .num_param = 4,
        .param = MIFparamTable,
        .num_inst_var = 0,
        .inst_var = NULL,
    },

    .DEVparam = NULL,
    .DEVmodParam = MIFmParam,
    .DEVload = MIFload,
    .DEVsetup = MIFsetup,
    .DEVunsetup = MIFunsetup,
    .DEVpzSetup = NULL,
    .DEVtemperature = NULL,
    .DEVtrunc = MIFtrunc,
    .DEVfindBranch = NULL,
    .DEVacLoad = MIFload,
    .DEVaccept = NULL,
    .DEVdestroy = NULL,
    .DEVmodDelete = MIFmDelete,
    .DEVdelete = MIFdelete,
    .DEVsetic = NULL,
    .DEVask = MIFask,
    .DEVmodAsk = MIFmAsk,
    .DEVpzLoad = NULL,
    .DEVconvTest = MIFconvTest,
    .DEVsenSetup = NULL,
    .DEVsenLoad = NULL,
    .DEVsenUpdate = NULL,
    .DEVsenAcLoad = NULL,
    .DEVsenPrint = NULL,
    .DEVsenTrunc = NULL,
    .DEVdisto = NULL,
    .DEVnoise = NULL,
    .DEVsoaCheck = NULL,
    .DEVinstSize = &val_sizeofMIFinstance,
    .DEVmodSize = &val_sizeofMIFmodel,

#ifdef CIDER
    .DEVdump = NULL,
    .DEVacct = NULL,
#endif
};

