int fooone_hot_cnt(int,int);
        int temp_enable[1024];
        int port_enable;
        int temp_clk[1024];
        int port_clk;
        int temp_reset[1024];
        int port_reset;
        int temp_out[1024];
        int port_out;