/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vone_hot_cnt.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_enable[1024];
        extern "C" int port_enable;
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_reset[1024];
        extern "C" int port_reset;
        extern "C" int temp_out[1024];
        extern "C" int port_out;
        extern "C" int fooone_hot_cnt(int,int);
        
        void int2arrone_hot_cnt(int  num, int array[], int n)
        {   
            for (int i = 0; i < n && num>=0; i++) 
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intone_hot_cnt(int array[],int n)
        {   
            int i,k=0;
            for (i = 0; i < n; i++) 
                k = 2 * k + array[i];
            return k;
        }
        
        int fooone_hot_cnt(int init,int count) 
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vone_hot_cnt* one_hot_cnt[1024];
            count--;
            if (init==0) 
            {
                one_hot_cnt[count]=new Vone_hot_cnt{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============one_hot_cnt : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("enable=%d\n", one_hot_cnt[count] ->enable);
				printf("clk=%d\n", one_hot_cnt[count] ->clk);
				printf("reset=%d\n", one_hot_cnt[count] ->reset);
				printf("out=%d\n", one_hot_cnt[count] ->out);
				one_hot_cnt[count]->enable = arr2intone_hot_cnt(temp_enable, port_enable);
				one_hot_cnt[count]->clk = arr2intone_hot_cnt(temp_clk, port_clk);
				one_hot_cnt[count]->reset = arr2intone_hot_cnt(temp_reset, port_reset);
				one_hot_cnt[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("enable=%d\n", one_hot_cnt[count] ->enable);
				printf("clk=%d\n", one_hot_cnt[count] ->clk);
				printf("reset=%d\n", one_hot_cnt[count] ->reset);
				printf("out=%d\n", one_hot_cnt[count] ->out);
				int2arrone_hot_cnt(one_hot_cnt[count] -> out, temp_out, port_out);

            }
            return 0;
        }