#include "ngspice/cm.h"
extern void cm_arbiter(Mif_Private_t *);
/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_arbiter.h"

        
void cm_arbiter(Mif_Private_t *mif_private) 
{
	Digital_State_t *_op_gnt3, *_op_gnt3_old;
	Digital_State_t *_op_gnt2, *_op_gnt2_old;
	Digital_State_t *_op_gnt1, *_op_gnt1_old;
	Digital_State_t *_op_gnt0, *_op_gnt0_old;

    static int inst_count=0;
    int count=0;
        
    if(mif_private->circuit.init)
    {   
        inst_count++;
        mif_private->param[0]->element[0].rvalue=inst_count;
        fooarbiter(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk=mif_private->conn[0]->size;

        port_rst=mif_private->conn[1]->size;

        port_req3=mif_private->conn[2]->size;

        port_req2=mif_private->conn[3]->size;

        port_req1=mif_private->conn[4]->size;

        port_req0=mif_private->conn[5]->size;

        port_gnt3=mif_private->conn[6]->size;

        port_gnt2=mif_private->conn[7]->size;

        port_gnt1=mif_private->conn[8]->size;

        port_gnt0=mif_private->conn[9]->size;
		cm_event_alloc(0,1*sizeof(Digital_State_t));
		cm_event_alloc(1,1*sizeof(Digital_State_t));
		cm_event_alloc(2,1*sizeof(Digital_State_t));
		cm_event_alloc(3,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
		{
			mif_private->conn[0]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
		{
			mif_private->conn[1]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
		{
			mif_private->conn[2]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
		{
			mif_private->conn[3]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
		{
			mif_private->conn[4]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
		{
			mif_private->conn[5]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}

		/*Retrieve Storage for output*/
		_op_gnt3 = _op_gnt3_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_gnt2 = _op_gnt2_old = (Digital_State_t *) cm_event_get_ptr(1,0);
		_op_gnt1 = _op_gnt1_old = (Digital_State_t *) cm_event_get_ptr(2,0);
		_op_gnt0 = _op_gnt0_old = (Digital_State_t *) cm_event_get_ptr(3,0);


	}
	else
	{
		_op_gnt3 = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_gnt3_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_gnt2 = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_gnt2_old = (Digital_State_t *) cm_event_get_ptr(1,2);
		_op_gnt1 = (Digital_State_t *) cm_event_get_ptr(2,2);
		_op_gnt1_old = (Digital_State_t *) cm_event_get_ptr(2,3);
		_op_gnt0 = (Digital_State_t *) cm_event_get_ptr(3,3);
		_op_gnt0_old = (Digital_State_t *) cm_event_get_ptr(3,4);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)mif_private->param[0]->element[0].rvalue;

    for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[0]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[1]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_rst[Ii]=0;            }
        else
        {
            temp_rst[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[2]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_req3[Ii]=0;            }
        else
        {
            temp_req3[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[3]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_req2[Ii]=0;            }
        else
        {
            temp_req2[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[4]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_req1[Ii]=0;            }
        else
        {
            temp_req1[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[5]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_req0[Ii]=0;            }
        else
        {
            temp_req0[Ii]=1;
        }
            }
	fooarbiter(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[6]->size;Ii++)
    {
        if(temp_gnt3[Ii]==0)
        {
            _op_gnt3[Ii]=ZERO;
            }
        else if(temp_gnt3[Ii]==1)
        {
            _op_gnt3[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[6]->port[Ii]->output.pvalue))->state = _op_gnt3[Ii];
            }
        else if(_op_gnt3[Ii] != _op_gnt3_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[6]->port[Ii]->output.pvalue))->state = _op_gnt3[Ii];
            mif_private->conn[6]->port[Ii]->delay = ((_op_gnt3[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[6]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[6]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[7]->size;Ii++)
    {
        if(temp_gnt2[Ii]==0)
        {
            _op_gnt2[Ii]=ZERO;
            }
        else if(temp_gnt2[Ii]==1)
        {
            _op_gnt2[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[7]->port[Ii]->output.pvalue))->state = _op_gnt2[Ii];
            }
        else if(_op_gnt2[Ii] != _op_gnt2_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[7]->port[Ii]->output.pvalue))->state = _op_gnt2[Ii];
            mif_private->conn[7]->port[Ii]->delay = ((_op_gnt2[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[7]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[7]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[8]->size;Ii++)
    {
        if(temp_gnt1[Ii]==0)
        {
            _op_gnt1[Ii]=ZERO;
            }
        else if(temp_gnt1[Ii]==1)
        {
            _op_gnt1[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[8]->port[Ii]->output.pvalue))->state = _op_gnt1[Ii];
            }
        else if(_op_gnt1[Ii] != _op_gnt1_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[8]->port[Ii]->output.pvalue))->state = _op_gnt1[Ii];
            mif_private->conn[8]->port[Ii]->delay = ((_op_gnt1[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[8]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[8]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[9]->size;Ii++)
    {
        if(temp_gnt0[Ii]==0)
        {
            _op_gnt0[Ii]=ZERO;
            }
        else if(temp_gnt0[Ii]==1)
        {
            _op_gnt0[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[9]->port[Ii]->output.pvalue))->state = _op_gnt0[Ii];
            }
        else if(_op_gnt0[Ii] != _op_gnt0_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[9]->port[Ii]->output.pvalue))->state = _op_gnt0[Ii];
            mif_private->conn[9]->port[Ii]->delay = ((_op_gnt0[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[9]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[9]->port[Ii]->output.pvalue))->strength = STRONG;
    }

}