/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

        
        #include <memory>
        #include <verilated.h>
        #include "Vmultitlv.h"
        #include <stdio.h>
        #include <stdio.h>
        #include <fstream>
        #include <stdlib.h>
        #include <string>
        #include <iostream>
        #include <cstring>
        using namespace std;
        
        extern "C" int temp_clk[1024];
        extern "C" int port_clk;
        extern "C" int temp_reset[1024];
        extern "C" int port_reset;
        extern "C" int temp_cyc_cnt[1024];
        extern "C" int port_cyc_cnt;
        extern "C" int temp_passed[1024];
        extern "C" int port_passed;
        extern "C" int temp_failed[1024];
        extern "C" int port_failed;
        extern "C" int foomultitlv(int,int);
        
        void int2arrmultitlv(int  num, int array[], int n)
        {   
            for (int i = 0; i < n && num>=0; i++) 
            {
                array[n-i-1] = num % 2;
                num /= 2;
                }
        }
        int arr2intmultitlv(int array[],int n)
        {   
            int i,k=0;
            for (i = 0; i < n; i++) 
                k = 2 * k + array[i];
            return k;
        }
        
        int foomultitlv(int init,int count) 
        {
            static VerilatedContext* contextp = new VerilatedContext;
            static Vmultitlv* multitlv[1024];
            count--;
            if (init==0) 
            {
                multitlv[count]=new Vmultitlv{contextp};
                contextp->traceEverOn(true);
            }
            else
            {
                contextp->timeInc(1);
                printf("=============multitlv : New Iteration===========");
                printf("\nInstance : %d\n",count);
                printf("\nInside foo before eval.....\n");
				printf("clk=%d\n", multitlv[count] ->clk);
				printf("reset=%d\n", multitlv[count] ->reset);
				printf("cyc_cnt=%d\n", multitlv[count] ->cyc_cnt);
				printf("passed=%d\n", multitlv[count] ->passed);
				printf("failed=%d\n", multitlv[count] ->failed);
				multitlv[count]->clk = arr2intmultitlv(temp_clk, port_clk);
				multitlv[count]->reset = arr2intmultitlv(temp_reset, port_reset);
				multitlv[count]->cyc_cnt = arr2intmultitlv(temp_cyc_cnt, port_cyc_cnt);
				multitlv[count]->eval();

                printf("\nInside foo after eval.....\n");
				printf("clk=%d\n", multitlv[count] ->clk);
				printf("reset=%d\n", multitlv[count] ->reset);
				printf("cyc_cnt=%d\n", multitlv[count] ->cyc_cnt);
				printf("passed=%d\n", multitlv[count] ->passed);
				printf("failed=%d\n", multitlv[count] ->failed);
				int2arrmultitlv(multitlv[count] -> passed, temp_passed, port_passed);
				int2arrmultitlv(multitlv[count] -> failed, temp_failed, port_failed);

            }
            return 0;
        }