#include "ngspice/cm.h"
extern void cm_traffic_light_controller(Mif_Private_t *);
/* This is cfunc.mod file auto generated by gen_con_info.py
        Developed by Sumanto Kar at IIT Bombay */

                
        #include <stdio.h>
        #include <math.h>
        #include <string.h>
        #include "sim_main_traffic_light_controller.h"

        
void cm_traffic_light_controller(Mif_Private_t *mif_private) 
{
	Digital_State_t *_op_light_M1, *_op_light_M1_old;
	Digital_State_t *_op_light_S, *_op_light_S_old;
	Digital_State_t *_op_light_MT, *_op_light_MT_old;
	Digital_State_t *_op_light_M2, *_op_light_M2_old;

    static int inst_count=0;
    int count=0;
        
    if(mif_private->circuit.init)
    {   
        inst_count++;
        mif_private->param[0]->element[0].rvalue=inst_count;
        footraffic_light_controller(0,inst_count);
        /* Allocate storage for output ports and set the load for input ports */

        
        port_clk=mif_private->conn[0]->size;

        port_rst=mif_private->conn[1]->size;

        port_light_M1=mif_private->conn[2]->size;

        port_light_S=mif_private->conn[3]->size;

        port_light_MT=mif_private->conn[4]->size;

        port_light_M2=mif_private->conn[5]->size;
		cm_event_alloc(0,3*sizeof(Digital_State_t));
		cm_event_alloc(1,3*sizeof(Digital_State_t));
		cm_event_alloc(2,3*sizeof(Digital_State_t));
		cm_event_alloc(3,1*sizeof(Digital_State_t));
		/* set the load for input ports. */
		int Ii;
		for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
		{
			mif_private->conn[0]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}
		for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
		{
			mif_private->conn[1]->port[Ii]->load=mif_private->param[1]->element[0].rvalue; 
		}

		/*Retrieve Storage for output*/
		_op_light_M1 = _op_light_M1_old = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_light_S = _op_light_S_old = (Digital_State_t *) cm_event_get_ptr(1,0);
		_op_light_MT = _op_light_MT_old = (Digital_State_t *) cm_event_get_ptr(2,0);
		_op_light_M2 = _op_light_M2_old = (Digital_State_t *) cm_event_get_ptr(3,0);


	}
	else
	{
		_op_light_M1 = (Digital_State_t *) cm_event_get_ptr(0,0);
		_op_light_M1_old = (Digital_State_t *) cm_event_get_ptr(0,1);
		_op_light_S = (Digital_State_t *) cm_event_get_ptr(1,1);
		_op_light_S_old = (Digital_State_t *) cm_event_get_ptr(1,2);
		_op_light_MT = (Digital_State_t *) cm_event_get_ptr(2,2);
		_op_light_MT_old = (Digital_State_t *) cm_event_get_ptr(2,3);
		_op_light_M2 = (Digital_State_t *) cm_event_get_ptr(3,3);
		_op_light_M2_old = (Digital_State_t *) cm_event_get_ptr(3,4);
	}

	//Formating data for sending it to client
	int Ii;
	count=(int)mif_private->param[0]->element[0].rvalue;

    for(Ii=0;Ii<mif_private->conn[0]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[0]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_clk[Ii]=0;            }
        else
        {
            temp_clk[Ii]=1;
        }
            }
    for(Ii=0;Ii<mif_private->conn[1]->size;Ii++)
    {
        if( ((Digital_t*)(mif_private->conn[1]->port[Ii]->input.pvalue))->state==ZERO )
        {
            temp_rst[Ii]=0;            }
        else
        {
            temp_rst[Ii]=1;
        }
            }
	footraffic_light_controller(1,count);

	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[2]->size;Ii++)
    {
        if(temp_light_M1[Ii]==0)
        {
            _op_light_M1[Ii]=ZERO;
            }
        else if(temp_light_M1[Ii]==1)
        {
            _op_light_M1[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[2]->port[Ii]->output.pvalue))->state = _op_light_M1[Ii];
            }
        else if(_op_light_M1[Ii] != _op_light_M1_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[2]->port[Ii]->output.pvalue))->state = _op_light_M1[Ii];
            mif_private->conn[2]->port[Ii]->delay = ((_op_light_M1[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[2]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[2]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[3]->size;Ii++)
    {
        if(temp_light_S[Ii]==0)
        {
            _op_light_S[Ii]=ZERO;
            }
        else if(temp_light_S[Ii]==1)
        {
            _op_light_S[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[3]->port[Ii]->output.pvalue))->state = _op_light_S[Ii];
            }
        else if(_op_light_S[Ii] != _op_light_S_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[3]->port[Ii]->output.pvalue))->state = _op_light_S[Ii];
            mif_private->conn[3]->port[Ii]->delay = ((_op_light_S[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[3]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[3]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[4]->size;Ii++)
    {
        if(temp_light_MT[Ii]==0)
        {
            _op_light_MT[Ii]=ZERO;
            }
        else if(temp_light_MT[Ii]==1)
        {
            _op_light_MT[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[4]->port[Ii]->output.pvalue))->state = _op_light_MT[Ii];
            }
        else if(_op_light_MT[Ii] != _op_light_MT_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[4]->port[Ii]->output.pvalue))->state = _op_light_MT[Ii];
            mif_private->conn[4]->port[Ii]->delay = ((_op_light_MT[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[4]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[4]->port[Ii]->output.pvalue))->strength = STRONG;
    }
	/* Scheduling event and processing them */
    for(Ii=0;Ii<mif_private->conn[5]->size;Ii++)
    {
        if(temp_light_M2[Ii]==0)
        {
            _op_light_M2[Ii]=ZERO;
            }
        else if(temp_light_M2[Ii]==1)
        {
            _op_light_M2[Ii]=ONE;
            }
        else
        {
            printf("Unknown value\n");
                }

        if(mif_private->circuit.anal_type == DC)
        {
            ((Digital_t*)(mif_private->conn[5]->port[Ii]->output.pvalue))->state = _op_light_M2[Ii];
            }
        else if(_op_light_M2[Ii] != _op_light_M2_old[Ii])
        {
            ((Digital_t*)(mif_private->conn[5]->port[Ii]->output.pvalue))->state = _op_light_M2[Ii];
            mif_private->conn[5]->port[Ii]->delay = ((_op_light_M2[Ii] == ZERO) ? mif_private->param[3]->element[0].rvalue : mif_private->param[2]->element[0].rvalue);
            }
        else
        {
            mif_private->conn[5]->port[Ii]->changed = FALSE;
            }
        ((Digital_t*)(mif_private->conn[5]->port[Ii]->output.pvalue))->strength = STRONG;
    }

}